import { css } from '@luminatick/ui/styled-system/css';

// Portal layout and content styles. Interactive controls receive their recipes
// from the shared Park UI components; these classes only compose the pages.
const page = css({ maxW: '5xl', mx: 'auto', px: { base: '4', md: '6' }, py: '8' });
const row = css({ display: 'flex', alignItems: 'center', gap: '3' });
const spread = css({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '3', flexWrap: 'wrap' });
const stack = css({ display: 'flex', flexDirection: 'column', gap: '4' });
const smallStack = css({ display: 'flex', flexDirection: 'column', gap: '2' });
const title = css({ fontSize: '2xl', fontWeight: 'bold', lineHeight: 'tight', color: 'text.primary' });
const heading = css({ fontSize: 'lg', fontWeight: 'semibold', color: 'text.primary' });
const label = css({ display: 'block', mb: '1', fontSize: 'sm', fontWeight: 'medium', color: 'text.primary' });
const muted = css({ fontSize: 'sm', color: 'text.muted' });
const tiny = css({ fontSize: 'xs', color: 'text.muted' });
const icon = css({ w: '4', h: '4', flexShrink: 0 });
const inset = css({ p: { base: '4', md: '6' } });
const full = css({ w: 'full' });
const form = css({ display: 'flex', flexDirection: 'column', gap: '5' });
const buttonIcon = css({ w: '4', h: '4', flexShrink: 0 });

export const p = {
  appLoading: page,
  layout: css({ minH: '100vh', bg: 'bg.canvas', color: 'text.primary' }),
  header: css({ bg: 'bg.surface', borderBottomWidth: '1px', borderColor: 'border.default' }),
  navInner: css({ maxW: '5xl', mx: 'auto', px: { base: '4', md: '6' } }),
  navRow: css({ display: 'flex', minH: '16', alignItems: 'center', justifyContent: 'space-between', gap: '4' }),
  brand: css({ display: 'inline-flex', alignItems: 'center', gap: '2', color: 'text.primary', fontWeight: 'bold', textDecoration: 'none' }),
  brandLogo: css({ h: '8', w: 'auto' }),
  brandName: css({ fontSize: 'lg' }),
  user: row,
  userLabel: css({ color: 'text.muted', fontSize: 'sm', display: { base: 'none', sm: 'inline' } }),
  logoutIcon: icon,
  main: page,
  routeLoading: page,
  routeError: css({ maxW: 'xl', mx: 'auto', p: '6', display: 'flex', flexDirection: 'column', gap: '3' }),

  authShell: css({ maxW: 'md', mx: 'auto', py: { base: '8', md: '16' } }),
  authHeading: css({ textAlign: 'center', mb: '6', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '2' }),
  authLoginHeading: css({ '& h2': { fontSize: '2xl', fontWeight: 'bold' }, '& p': { color: 'text.muted' } }),
  authForm: form,
  authLegend: label,
  authMethods: css({ display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gap: '2' }),
  authMethod: css({ w: 'full', minH: '10' }),
  authTurnstile: css({ display: 'flex', justifyContent: 'center' }),
  authSubmit: css({ w: 'full', justifyContent: 'center' }),
  authIcon: buttonIcon,
  authSpinner: css({ w: '4', h: '4', animation: 'spin 1s linear infinite' }),
  authStatus: tiny,
  verifyHeading: smallStack,
  verifyTitle: title,
  verifyCopy: muted,
  verifyLoading: css({ py: '12' }),
  verifyLoadingTitle: heading,
  verifyBack: css({ mt: '4', textAlign: 'center' }),
  verifyPinWrap: css({ display: 'flex', justifyContent: 'center', minW: '0' }),
  visuallyHidden: css({ srOnly: true }),
  formControl: full,

  ticketList: stack,
  ticketListHeader: spread,
  ticketListTitle: title,
  ticketListCreate: row,
  ticketListIcon: icon,
  ticketDialog: css({ maxW: 'lg', w: 'full' }),
  ticketDialogTitle: heading,
  ticketDialogStatus: muted,
  ticketForm: form,
  ticketField: smallStack,
  ticketFieldInput: full,
  ticketActions: css({ display: 'flex', justifyContent: 'flex-end', gap: '2', flexWrap: 'wrap' }),
  ticketSubmit: row,
  ticketSpinner: css({ w: '4', h: '4', animation: 'spin 1s linear infinite' }),
  ticketEmpty: inset,
  ticketEmptyCreate: row,
  ticketLoading: page,
  ticketError: page,
  ticketListItems: css({ listStyle: 'none', m: '0', p: '0' }),
  ticketListItem: css({ borderBottomWidth: '1px', borderColor: 'border.default', _last: { borderBottomWidth: '0' } }),
  ticketListLink: css({ display: 'block', p: '4', color: 'text.primary' }),
  ticketListRow: spread,
  ticketRowMain: row,
  ticketReference: css({ fontFamily: 'tabular', fontSize: 'sm', fontWeight: 'bold' }),
  ticketSubject: css({ fontSize: 'md', fontWeight: 'semibold' }),
  ticketStatus: css({ textTransform: 'capitalize' }),
  ticketListMeta: css({ display: 'flex', gap: '2', mt: '2', color: 'text.muted', fontSize: 'xs' }),
  ticketPriority: css({ textTransform: 'capitalize' }),
  statusOpen: css({ bg: 'info.surface', color: 'info.text' }),
  statusPending: css({ bg: 'warning.surface', color: 'warning' }),
  statusResolved: css({ bg: 'bg.subtle', color: 'text.primary' }),
  statusClosed: css({ bg: 'bg.subtle', color: 'text.muted' }),

  ticketDetail: stack,
  ticketDetailHeader: css({ display: 'flex', alignItems: 'flex-start', gap: '4' }),
  ticketDetailBack: css({ display: 'inline-grid', placeItems: 'center', minW: '10', minH: '10', rounded: 'md', color: 'text.primary' }),
  ticketDetailTitle: css({ display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: '2', fontSize: '2xl', fontWeight: 'bold' }),
  ticketDetailMeta: muted,
  chatBackIcon: icon,
  chatStatusPill: css({ textTransform: 'capitalize' }),
  chatStatus: muted,
  chatSurface: css({ overflow: 'hidden' }),
  chatItem: css({ display: 'flex', flexDirection: 'column', gap: '1' }),
  chatItemCustomer: css({ alignItems: 'flex-end' }),
  chatItemSupport: css({ alignItems: 'flex-start' }),
  chatMeta: row,
  chatMetaName: css({ fontSize: 'xs', fontWeight: 'semibold' }),
  chatMetaTime: tiny,
  message: css({ minW: '0', maxW: '85%', px: '4', py: '3', rounded: 'lg', overflowWrap: 'anywhere' }),
  messageCustomer: css({ bg: 'accent.primary', color: 'bg.surface' }),
  messageSupport: css({ bg: 'bg.subtle', color: 'text.primary' }),
  chatBody: css({ minW: '0', whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', lineHeight: 'relaxed' }),
  chatAttachments: css({ display: 'flex', flexDirection: 'column', gap: '1', mt: '2' }),
  chatAttachment: css({ justifyContent: 'flex-start', gap: '1', maxW: 'full' }),
  chatAttachmentCustomer: css({ color: 'inherit' }),
  chatAttachmentSupport: css({ color: 'text.primary' }),
  chatAttachmentIcon: icon,
  chatAttachmentName: css({ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }),
  chatAttachmentNameCompact: css({ maxW: '48' }),
  chatAttachmentSize: tiny,
  chatPagination: css({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '2', px: '4', py: '2', borderTopWidth: '1px', borderColor: 'border.default' }),
  chatPaginationStatus: tiny,
  chatComposer: css({ p: '4', borderTopWidth: '1px', borderColor: 'border.default' }),
  chatComposerForm: form,
  chatReplyRequirement: tiny,
  chatReplyInput: full,
  chatAttachmentList: smallStack,
  chatAttachmentItem: row,
  chatAttachmentRemove: css({ ml: 'auto' }),
  chatAttachmentRemoveIcon: icon,
  chatReplyActions: spread,
  chatAttachButton: row,
  chatAttachIcon: icon,
  chatSendButton: row,
  chatSendIcon: icon,
  emptyState: inset,
  emptyError: inset,
  emptyActions: row,

  slaCardInset: css({ p: '4' }),
  slaHeading: heading,
  slaState: css({ py: '4' }),
  slaStatus: muted,
  slaTargets: css({ display: 'grid', gridTemplateColumns: { base: '1fr', sm: 'repeat(2, minmax(0, 1fr))' }, gap: '2', mt: '3', listStyle: 'none', p: '0' }),
  slaTarget: css({ p: '3', rounded: 'md', bg: 'bg.subtle' }),
  slaTargetName: css({ fontSize: 'sm', fontWeight: 'semibold' }),
  slaTargetStatus: muted,
  slaTargetDue: tiny,

  localCapture: page,
  localCaptureTitle: title,
  localCaptureIntro: muted,
  localCaptureActions: css({ display: 'flex', gap: '2', mt: '4', flexWrap: 'wrap' }),
  localCaptureStatus: css({ color: 'text.muted', my: '4' }),
  localCaptureSection: stack,
  localCaptureHeading: heading,
  localCaptureEmpty: inset,
  localCaptureMessage: css({ p: '4', bg: 'bg.surface', borderWidth: '1px', borderColor: 'border.default', rounded: 'md' }),
  localCaptureMessageTitle: heading,
  localCaptureMessageMeta: tiny,
  localCapturePayload: css({ mt: '2', p: '3', overflowX: 'auto', bg: 'bg.subtle', fontSize: 'xs' }),
} as const;
