name: Feature proposal
description: Describe a problem and a proposed improvement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: Who is affected and what are they trying to achieve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed behaviour and alternatives
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: What would demonstrate success?
