import { absoluteCenter, badge, button, code, group, heading, icon, input, inputAddon, kbd, link, skeleton, spinner, text, textarea, accordion, alert, avatar, breadcrumb, card, carousel, checkbox, clipboard, collapsible, colorPicker, combobox, datePicker, dialog, drawer, editable, field, fieldset, fileUpload, hoverCard, inputGroup, menu, numberInput, pagination, pinInput, popover, progress, radioCardGroup, radioGroup, ratingGroup, scrollArea, segmentGroup, select, slider, splitter, switchRecipe, table, tabs, tagsInput, toast, toggleGroup, tooltip } from './src/theme/recipes/index';

const parkRegistryRecipes = { absoluteCenter: absoluteCenter, badge: badge, button: button, code: code, group: group, heading: heading, icon: icon, input: input, inputAddon: inputAddon, kbd: kbd, link: link, skeleton: skeleton, spinner: spinner, text: text, textarea: textarea };
const parkRegistrySlotRecipes = { accordion: accordion, alert: alert, avatar: avatar, breadcrumb: breadcrumb, card: card, carousel: carousel, checkbox: checkbox, clipboard: clipboard, collapsible: collapsible, colorPicker: colorPicker, combobox: combobox, datePicker: datePicker, dialog: dialog, drawer: drawer, editable: editable, field: field, fieldset: fieldset, fileUpload: fileUpload, hoverCard: hoverCard, inputGroup: inputGroup, menu: menu, numberInput: numberInput, pagination: pagination, pinInput: pinInput, popover: popover, progress: progress, radioCardGroup: radioCardGroup, radioGroup: radioGroup, ratingGroup: ratingGroup, scrollArea: scrollArea, segmentGroup: segmentGroup, select: select, slider: slider, splitter: splitter, switchRecipe: switchRecipe, table: table, tabs: tabs, tagsInput: tagsInput, toast: toast, toggleGroup: toggleGroup, tooltip: tooltip };

/**
 * Build-time Panda configuration for the shared Park-compatible layer.
 * Keep this file dependency-light so consumers can import the UI contract
 * without loading a styling runtime.
 */
export default {
  preflight: false,
  jsxFramework: 'react',
  globalCss: {
    'html, body, #root': { fontFamily: 'primary', color: 'text.primary', background: 'bg.canvas' },
    '[data-tabular]': { fontFamily: 'tabular', fontFeatureSettings: '"tnum" 1, "cv01" 1', fontVariantNumeric: 'tabular-nums' },
  },
  include: ['./src/**/*.{ts,tsx}'],
  outdir: './src/styles/generated',
  theme: {
    extend: {
      semanticTokens: {
        colors: {
          'bg.canvas': { value: { base: '#f8fafc', _dark: '#0f1115' } },
          'bg.surface': { value: { base: '#ffffff', _dark: '#1a1d23' } },
          'bg.input': { value: { base: '#f1f5f9', _dark: '#1e293b' } },
          'text.primary': { value: { base: '#1e293b', _dark: '#e2e8f0' } },
          'text.muted': { value: { base: '#64748b', _dark: '#94a3b8' } },
          'border.input': { value: { base: '#cbd5e1', _dark: '#334155' } },
          'border.focus': { value: { base: '#3b82f6', _dark: '#60a5fa' } },
          'accent.primary': { value: { base: '#334155', _dark: '#cbd5e1' } },
          'icon.primary': { value: { base: '#1e293b', _dark: '#e2e8f0' } },
          'icon.muted': { value: { base: '#64748b', _dark: '#94a3b8' } },
          'icon.disabled': { value: { base: '#94a3b8', _dark: '#475569' } },
          'icon.selected': { value: { base: '#3b82f6', _dark: '#60a5fa' } },
          'icon.critical': { value: { base: '#b91c1c', _dark: '#fca5a5' } },
          'icon.inverse': { value: { base: '#f8fafc', _dark: '#e2e8f0' } },
          'gray.surface.bg': { value: { base: '#ffffff', _dark: '#1a1d23' } },
          'gray.subtle.bg': { value: { base: '#f1f5f9', _dark: '#1e293b' } },
          canvas: { value: 'var(--tocyn-color-surface)' },
          panel: { value: 'var(--tocyn-color-surface-panel)' },
          muted: { value: 'var(--tocyn-color-surface-muted)' },
          text: { value: 'var(--tocyn-color-text)' },
          textMuted: { value: 'var(--tocyn-color-text-muted)' },
          focus: { value: 'var(--tocyn-color-focus)' },
          selected: { value: 'var(--tocyn-color-selected)' },
          divider: { value: 'var(--tocyn-color-divider)' },
          critical: { value: 'var(--tocyn-color-critical)' },
          'critical.surface': { value: 'var(--tocyn-color-critical-surface)' },
          'critical.border': { value: 'var(--tocyn-color-critical-border)' },
          warning: { value: 'var(--tocyn-color-warning-text)' },
          'warning.surface': { value: 'var(--tocyn-color-warning-surface)' },
          'warning.border': { value: 'var(--tocyn-color-warning-border)' },
          'info.surface': { value: 'var(--tocyn-color-info-surface)' },
          'info.text': { value: 'var(--tocyn-color-info-text)' },
          inverse: { value: 'var(--tocyn-color-inverse)' },
          'bg.default': { value: 'var(--tocyn-color-surface-panel)' },
          'bg.subtle': { value: 'var(--tocyn-color-surface-muted)' },
          'fg.default': { value: 'var(--tocyn-color-text)' },
          'fg.muted': { value: 'var(--tocyn-color-text-muted)' },
          'border.default': { value: 'var(--tocyn-color-divider)' },
        },
      },
      tokens: {
        fonts: {
          primary: { value: "'Atkinson Hyperlegible', sans-serif" },
          tabular: { value: "'Inter', sans-serif" },
        },
        radii: {
          l1: { value: '0.25rem' },
          l2: { value: '0.5rem' },
          l3: { value: '0.75rem' },
          control: { value: '{radii.l2}' },
          panel: { value: '{radii.l3}' },
        },
        shadows: {
          xs: { value: '0 1px 2px rgb(15 23 42 / 6%)' },
          sm: { value: '0 2px 6px rgb(15 23 42 / 8%)' },
          md: { value: '0 8px 20px rgb(15 23 42 / 10%)' },
          lg: { value: '0 16px 32px rgb(15 23 42 / 12%)' },
          xl: { value: '0 20px 40px rgb(15 23 42 / 14%)' },
          '2xl': { value: '0 24px 48px rgb(15 23 42 / 16%)' },
        },
        sizes: { target: { value: 'var(--tocyn-target-min)' } },
      },
      textStyles: {
        body: { value: { fontFamily: 'primary', fontSize: '1rem', lineHeight: '1.5' } },
        tabular: { value: { fontFamily: 'tabular', fontFeatureSettings: '"tnum" 1, "cv01" 1', fontVariantNumeric: 'tabular-nums', lineHeight: '1.4' } },
      },
      slotRecipes: {
        ...parkRegistrySlotRecipes,
        page: {
          className: 'page',
          slots: [
            'root', 'header', 'content', 'grid', 'section',
            'settingsSections', 'settingsField', 'settingsError', 'settingsHelp',
            'knowledgeWorkspace', 'knowledgeSidebar', 'knowledgeContent', 'knowledgeTable', 'knowledgeRow', 'knowledgeSearch', 'knowledgePreview',
            'knowledgeCategoryRow', 'knowledgeCategoryRowSelected', 'knowledgeCategoryMain', 'knowledgeCategoryActions', 'knowledgeCategoryChildren', 'knowledgeCategoryList', 'knowledgeCategorySpacer', 'knowledgeCategoryButton', 'knowledgeDeleteActions', 'knowledgeStatusBadge',
            'accountGrid', 'accountIdentityName', 'accountIdentityEmail',
            'inboxWorkspace', 'inboxList', 'inboxDetail', 'inboxHeader', 'inboxControls', 'inboxControlCell', 'inboxControlLabel', 'inboxMetrics', 'inboxSearch', 'inboxToolbar', 'inboxRows', 'inboxRow', 'inboxTable', 'inboxEmpty', 'inboxMobileHidden', 'inboxTableMobileHidden', 'inboxStatus', 'inboxPriority', 'inboxMobileNote', 'inboxTableResponsive', 'inboxTitleRow', 'inboxRowCopy', 'inboxRowSubject', 'inboxRowCustomer', 'inboxRowDate', 'inboxRowPreview', 'inboxRowMeta', 'inboxToolbarGroup', 'inboxPagination', 'inboxHiddenLabel',
            'metricStrip', 'metricCard', 'metricIcon', 'panels', 'priorityList', 'priorityRow', 'progressTrack', 'progressFill', 'overviewGrid', 'overviewCard', 'overviewFooter',
          ],
          base: {
            root: { width: '100%', minWidth: '0', minHeight: '100%', background: 'bg.canvas', color: 'text.primary', fontFamily: 'primary' },
            header: { display: 'flex', flexWrap: 'wrap', alignItems: 'flex-start', justifyContent: 'space-between', gap: '1.5rem', marginBottom: '2rem' },
            content: { width: '100%', minWidth: '0', maxWidth: '72rem', marginInline: 'auto', padding: '2rem 1rem' },
            grid: { display: 'grid', gap: '1rem', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
            section: { minWidth: '0' },
            settingsSections: { display: 'grid', gap: '1rem' },
            settingsField: { display: 'grid', gap: '0.375rem' },
            settingsError: { display: 'flex', alignItems: 'flex-start', gap: '1rem', marginBottom: '1.5rem', border: '1px solid', borderColor: 'critical.border', borderRadius: 'l2', background: 'critical.surface', color: 'critical', padding: { base: '1rem', md: '1.5rem' }, '& svg': { width: '2rem', height: '2rem', flexShrink: '0' } },
            settingsHelp: { marginTop: '0.25rem', color: 'text.muted', fontSize: '0.875rem' },
            knowledgeWorkspace: { display: 'grid', minWidth: '0', gridTemplateColumns: { base: '1fr', md: 'minmax(16rem, 20rem) minmax(0, 1fr)' }, gap: '1rem', alignItems: 'start' },
            knowledgeSidebar: { minWidth: '0', position: 'sticky', top: '1rem' },
            knowledgeContent: { minWidth: '0', overflow: 'hidden' },
            knowledgeTable: { width: '100%', borderCollapse: 'collapse', tableLayout: 'fixed' },
            knowledgeRow: { borderTop: '1px solid', borderColor: 'border.default', _hover: { background: 'bg.subtle' } },
            knowledgeSearch: { display: 'grid', gap: '0.5rem' },
            knowledgePreview: { display: 'grid', gap: '0.5rem', padding: '0.75rem', borderRadius: 'l2', background: 'bg.subtle' },
            knowledgeCategoryRow: { display: 'flex', minWidth: '0', alignItems: 'center', justifyContent: 'space-between', gap: '0.5rem', borderRadius: 'l2', paddingBlock: '0.25rem', paddingInlineStart: 'calc(var(--tocyn-category-depth, 0) * 1.5rem + 0.375rem)', paddingInlineEnd: '0.375rem' },
            knowledgeCategoryRowSelected: { background: 'bg.subtle', color: 'fg.default' },
            knowledgeCategoryMain: { display: 'flex', minWidth: '0', alignItems: 'center', gap: '0.25rem', flex: '1' },
            knowledgeCategoryActions: { display: 'flex', alignItems: 'center', gap: '0.25rem', flexShrink: '0' },
            knowledgeCategoryChildren: { marginInlineStart: '0.75rem', borderInlineStart: '1px solid', borderColor: 'border.default', paddingInlineStart: '0.375rem' },
            knowledgeCategoryList: { display: 'grid', gap: '0.125rem' },
            knowledgeCategorySpacer: { display: 'inline-block', width: '2.25rem', height: '2.25rem', flexShrink: '0' },
            knowledgeCategoryButton: { display: 'inline-flex', minWidth: '0', minHeight: '2.5rem', flex: '1', alignItems: 'center', justifyContent: 'flex-start', gap: '0.5rem', overflow: 'hidden', border: '0', background: 'transparent', color: 'fg.default', padding: '0.5rem', textAlign: 'start', _hover: { background: 'bg.subtle' } },
            knowledgeDeleteActions: { display: 'flex', justifyContent: 'flex-end', gap: '0.75rem', marginTop: '1rem' },
            knowledgeStatusBadge: { display: 'inline-flex', minHeight: '1.75rem', alignItems: 'center', borderRadius: 'full', background: 'bg.subtle', color: 'text.muted', padding: '0.25rem 0.625rem', fontSize: '0.8125rem', fontWeight: '600', '&[data-status="active"]': { background: 'info.surface', color: 'info.text' }, '&[data-status="processing"]': { background: 'warning.surface', color: 'warning' }, '&[data-status="error"]': { background: 'critical.surface', color: 'critical' }, '&[data-tier="sop"]': { background: 'bg.input', color: 'text.primary' } },
            accountGrid: { display: 'grid', gridTemplateColumns: { base: '1fr', md: 'repeat(2, minmax(0, 1fr))' }, gap: '1rem', marginBlock: '1rem' },
            accountIdentityName: { margin: '0', fontWeight: '600' },
            accountIdentityEmail: { overflow: 'hidden', margin: '0.25rem 0 0', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
            inboxWorkspace: { display: 'flex', minWidth: '0', minHeight: '0', width: '100%', height: '100%' },
            inboxList: { display: 'flex', minWidth: '0', minHeight: '0', flex: '1', flexDirection: 'column', overflow: 'hidden' },
            inboxDetail: { display: 'flex', minWidth: '0', minHeight: '0', flex: '1', flexDirection: 'column', overflow: 'auto', background: 'bg.canvas' },
            inboxHeader: { display: 'grid', gap: '1rem', padding: '1.5rem 1.5rem 1rem', borderBottom: '1px solid', borderColor: 'border.default', background: 'bg.surface' },
            inboxControls: { display: 'grid', gridTemplateColumns: { base: '1fr', md: 'repeat(3, minmax(0, 1fr))' }, gap: '0.75rem' },
            inboxControlCell: { display: 'grid', minWidth: '0', gap: '0.375rem' },
            inboxControlLabel: { color: 'text.muted', fontSize: '0.8125rem', fontWeight: '600' },
            inboxMetrics: { display: 'grid', gridTemplateColumns: { base: 'repeat(2, minmax(0, 1fr))', lg: 'repeat(4, minmax(0, 1fr))' }, gap: '0.75rem' },
            inboxSearch: { position: 'relative', minWidth: '0' },
            inboxToolbar: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '1rem', padding: '0.75rem 1.5rem', borderBottom: '1px solid', borderColor: 'border.default' },
            inboxRows: { display: 'flex', minHeight: '0', flex: '1', flexDirection: 'column', overflowY: 'auto' },
            inboxRow: { display: 'grid', gap: '0.5rem', borderBottom: '1px solid', borderColor: 'border.default', padding: '1rem 1.5rem', _hover: { background: 'bg.subtle' } },
            inboxTable: { width: '100%', borderCollapse: 'collapse', tableLayout: 'fixed' },
            inboxEmpty: { display: 'flex', minHeight: '16rem', alignItems: 'center', justifyContent: 'center', padding: '2rem' },
            inboxMobileHidden: { display: { base: 'none', lg: 'block' } },
            inboxTableMobileHidden: { display: { base: 'block', md: 'none' } },
            inboxStatus: { display: 'inline-flex', minHeight: '1.75rem', alignItems: 'center', borderRadius: 'full', background: 'bg.subtle', color: 'text.muted', padding: '0.25rem 0.625rem', fontSize: '0.8125rem', fontWeight: '600', '&[data-status="open"]': { background: 'info.surface', color: 'info.text' }, '&[data-status="pending"]': { background: 'warning.surface', color: 'warning' } },
            inboxPriority: { display: 'inline-flex', alignItems: 'center', gap: '0.25rem', color: 'text.muted', textTransform: 'capitalize', '&[data-priority="normal"]': { color: 'info.text' }, '&[data-priority="high"]': { color: 'warning' }, '&[data-priority="urgent"]': { color: 'critical' } },
            inboxMobileNote: { display: { base: 'block', sm: 'none' }, color: 'text.muted', fontSize: '0.875rem' },
            inboxTableResponsive: { display: { base: 'none', sm: 'block' }, overflowX: 'auto' },
            inboxTitleRow: { display: 'flex', minWidth: '0', alignItems: 'flex-start', justifyContent: 'space-between', gap: '1rem' },
            inboxRowCopy: { display: 'grid', minWidth: '0', gap: '0.125rem' },
            inboxRowSubject: { margin: '0', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontWeight: '600' },
            inboxRowCustomer: { margin: '0', overflow: 'hidden', color: 'text.muted', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontSize: '0.875rem' },
            inboxRowDate: { flexShrink: '0', color: 'text.muted', fontSize: '0.8125rem' },
            inboxRowPreview: { margin: '0', overflow: 'hidden', color: 'text.muted', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontSize: '0.875rem' },
            inboxRowMeta: { display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: '0.5rem', color: 'text.muted', fontSize: '0.8125rem' },
            inboxToolbarGroup: { display: 'flex', alignItems: 'center', gap: '0.75rem' },
            inboxPagination: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '1rem', borderTop: '1px solid', borderColor: 'border.default', padding: '0.75rem 1.5rem' },
            inboxHiddenLabel: { position: 'absolute', width: '1px', height: '1px', overflow: 'hidden', clip: 'rect(0 0 0 0)', whiteSpace: 'nowrap' },
            metricStrip: { display: 'grid', gridTemplateColumns: { base: 'repeat(2, minmax(0, 1fr))', lg: 'repeat(4, minmax(0, 1fr))' }, gap: '1rem' },
            metricCard: { minWidth: '0' },
            metricIcon: { display: 'inline-flex', width: '2.25rem', height: '2.25rem', alignItems: 'center', justifyContent: 'center', borderRadius: 'l2', background: 'bg.subtle', color: 'text.primary', '&[data-tone="blue"]': { background: 'info.surface', color: 'info.text' }, '&[data-tone="green"]': { background: 'rgba(16,185,129,0.12)', color: 'rgba(5,150,105,1)' }, '&[data-tone="amber"]': { background: 'warning.surface', color: 'warning' }, '&[data-tone="neutral"]': { background: 'bg.input', color: 'text.muted' } },
            panels: { display: 'grid', gridTemplateColumns: { base: '1fr', lg: 'repeat(2, minmax(0, 1fr))' }, gap: '1rem' },
            priorityList: { display: 'grid', gap: '0.75rem' },
            priorityRow: { display: 'grid', gap: '0.375rem' },
            progressTrack: { width: '100%', height: '0.5rem', overflow: 'hidden', borderRadius: 'full', background: 'bg.subtle' },
            progressFill: { height: '100%', width: 'var(--tocyn-progress, 0%)', borderRadius: 'full', background: 'accent.primary', transition: 'width 150ms ease', '&[data-tone="urgent"]': { background: 'critical' }, '&[data-tone="high"]': { background: 'warning' }, '&[data-tone="normal"]': { background: 'border.focus' }, '&[data-tone="low"]': { background: 'border.default' } },
            overviewGrid: { display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gap: '0.75rem' },
            overviewCard: { minWidth: '0' },
            overviewFooter: { margin: '1rem 0 0', color: 'text.muted', fontSize: '0.875rem' },
          },
          variants: {
            kind: {
              dashboard: { content: { maxWidth: '88rem', display: 'grid', gap: '2rem' } },
              knowledge: { content: { maxWidth: '96rem', display: 'grid', gap: '1.5rem' } },
              inbox: { content: { maxWidth: 'none', padding: '0' } },
              settings: { content: { maxWidth: '56rem' } },
              account: { content: { maxWidth: '72rem' } },
            },
          },
          compoundVariants: [
            { kind: 'settings', css: { grid: { gridTemplateColumns: '1fr' }, settingsSections: { maxWidth: '56rem', marginInline: 'auto' } } },
            { kind: 'knowledge', css: { knowledgeWorkspace: { gridTemplateColumns: 'minmax(15rem, 20rem) minmax(0, 1fr)' } } },
            { kind: 'inbox', css: { inboxControls: { gridTemplateColumns: 'repeat(3, minmax(0, 1fr))' } } },
          ],
          defaultVariants: { kind: 'dashboard' },
        },
        globalSearch: {
          className: 'globalSearch',
          slots: ['root', 'inputShell', 'icon', 'input', 'shortcut', 'divider', 'scope', 'popover', 'status', 'results', 'result', 'preview'],
          base: {
            root: { position: 'relative', display: 'flex', flex: '1', minWidth: '0', width: '100%', maxWidth: '32rem', marginInline: 'auto', alignItems: 'center', border: '1px solid', borderColor: 'border.input', borderRadius: 'l2', background: 'bg.input', color: 'text.primary' },
            inputShell: { position: 'relative', display: 'flex', flex: '1', minWidth: '0', alignItems: 'center' },
            icon: { position: 'absolute', insetInlineStart: '0.75rem', width: '1rem', height: '1rem', color: 'icon.muted', pointerEvents: 'none', zIndex: '1' },
            input: { minWidth: '0', minHeight: '2.75rem', border: '0', borderRadius: 'l2', background: 'transparent', paddingInline: '2.5rem 3rem', outline: '0', _focusVisible: { outline: '2px solid', outlineColor: 'border.focus', outlineOffset: '-2px' } },
            shortcut: { position: 'absolute', insetInlineEnd: '0.75rem', color: 'text.muted', fontSize: '0.75rem', pointerEvents: 'none', whiteSpace: 'nowrap' },
            divider: { width: '1px', height: '1.5rem', flexShrink: '0', background: 'border.input' },
            scope: { display: 'flex', flexShrink: '0', width: '5.25rem', minWidth: '0', alignItems: 'stretch' },
            popover: { position: 'absolute', insetBlockStart: 'calc(100% + 0.5rem)', insetInline: '0', zIndex: '50', maxHeight: 'min(24rem, 60vh)', overflowY: 'auto', border: '1px solid', borderColor: 'border.input', borderRadius: 'l2', background: 'bg.surface', color: 'text.primary', padding: '0.75rem', boxShadow: 'sm' },
            status: { color: 'text.muted', fontSize: '0.875rem' },
            results: { maxHeight: '16rem', overflow: 'auto', display: 'flex', flexDirection: 'column', gap: '0.125rem' },
            result: { display: 'flex', width: '100%', minHeight: '2.5rem', alignItems: 'center', border: '0', borderRadius: 'l2', background: 'transparent', color: 'text.primary', padding: '0.5rem 0.75rem', textAlign: 'start', textDecoration: 'none', _hover: { background: 'bg.subtle' }, _focusVisible: { outline: '2px solid', outlineColor: 'border.focus', outlineOffset: '2px' } },
            preview: { border: '1px solid', borderColor: 'border.default', borderRadius: 'l2', background: 'bg.subtle', color: 'text.primary', padding: '0.75rem' },
          },
        },
        shell: {
          className: 'shell',
          slots: ['root', 'sidebar', 'main', 'header', 'content', 'navigation', 'navigationLink', 'navigationLinkLabelled', 'navigationLinkIcon', 'navigationIcon', 'sidebarDesktop', 'sidebarLabelled', 'sidebarCompact', 'logoLink', 'logo', 'mobileDialog', 'mobileDialogLabelled', 'mobileDialogCompact', 'mobileContent', 'mobileClose', 'mobileTrigger', 'personaTrigger', 'personaAvatar', 'personaStatus', 'accountMenu', 'accountSummary', 'accountSummaryName', 'accountSummaryEmail', 'menuItem', 'activityTrigger', 'activityPopover', 'activityBadge', 'activityHeader', 'activityTitle', 'activityRefresh', 'activityDismiss', 'activityMessage', 'activityWarning', 'activityRetry', 'activityList', 'activityRow', 'activityItem', 'activitySubject', 'activityMoreWrap', 'activityMore', 'connectionWrap', 'connectionPopover', 'connectionButton', 'connectionDot', 'connectionChevron', 'reconnectDivider', 'reconnectButton', 'icon', 'menuIcon', 'smallIcon', 'dismissIcon', 'rootInbox', 'rootStandard', 'contentInbox', 'contentStandard', 'contentPadded'],
          base: {
            root: { display: 'flex', width: '100%', minHeight: '100dvh', background: 'bg.canvas', color: 'text.primary', fontFamily: 'primary' },
            sidebar: { display: 'flex', flexDirection: 'column', flexShrink: '0', width: '4rem', minHeight: '100dvh', background: 'inverse', color: 'icon.inverse', borderRight: '1px solid', borderColor: 'border.default', padding: '1rem 0.5rem' },
            main: { display: 'flex', flex: '1', minWidth: '0', minHeight: '100dvh', flexDirection: 'column', background: 'bg.canvas' },
            header: { display: 'flex', flexShrink: '0', minHeight: '4rem', alignItems: 'center', gap: '1rem', borderBottom: '1px solid', borderColor: 'border.default', background: 'bg.surface', padding: '0.5rem 1rem' },
            content: { display: 'flex', flex: '1', minWidth: '0', minHeight: '0', flexDirection: 'column' },
            navigation: { display: 'flex', flex: '1', width: '100%', flexDirection: 'column', alignItems: 'center', gap: '0.5rem', marginTop: '1.5rem' },
            navigationLink: { display: 'inline-flex', minWidth: '2.75rem', minHeight: '2.75rem', alignItems: 'center', justifyContent: 'center', borderRadius: 'l2', color: 'icon.inverse', padding: '0.5rem', transition: 'colors', _hover: { background: 'bg.subtle', color: 'icon.inverse' }, _focusVisible: { outline: '2px solid', outlineColor: 'border.focus', outlineOffset: '2px' }, '&[aria-current="page"]': { background: 'bg.subtle', color: 'icon.selected', '& svg': { color: 'icon.selected' } } },
            navigationLinkLabelled: { width: '100%', justifyContent: 'flex-start', gap: '0.75rem', padding: '0.5rem 0.75rem' },
            navigationLinkIcon: { position: 'relative', width: '100%', aspectRatio: '1' },
            navigationIcon: { flexShrink: '0', width: '2.5rem', height: '2.5rem', color: 'icon.inverse' },
            sidebarDesktop: { flexShrink: '0', display: { base: 'none', lg: 'block' } },
            sidebarLabelled: { width: '16rem' },
            sidebarCompact: { width: '4rem' },
            logoLink: { display: 'flex', alignItems: 'center', justifyContent: 'center', width: '2.75rem', height: '2.75rem', marginBottom: '2rem' },
            logo: { width: '2.5rem', height: '2.5rem', objectFit: 'contain' },
            mobileDialog: { position: 'fixed', insetBlock: '0', insetInlineStart: '0', zIndex: '50', width: '5rem', height: '100dvh', overflowY: 'auto', margin: '0', padding: '0.5rem' },
            mobileDialogLabelled: { width: '14rem', maxWidth: '90vw' },
            mobileDialogCompact: { width: '5rem' },
            mobileContent: { height: 'calc(100dvh - 4rem)' },
            mobileClose: { padding: '0.5rem' },
            mobileTrigger: { display: { base: 'inline-flex', lg: 'none' }, padding: '0.5rem' },
            personaTrigger: { position: 'relative', display: 'inline-flex', flexShrink: '0', alignItems: 'center', justifyContent: 'center', minWidth: '2.75rem', minHeight: '2.75rem', padding: '0.125rem' },
            personaAvatar: { width: '2.5rem', height: '2.5rem' },
            personaStatus: { position: 'absolute', insetBlockEnd: '0.125rem', insetInlineEnd: '0.125rem', width: '0.625rem', height: '0.625rem', borderRadius: 'full', background: 'rgba(34,197,94,1)' },
            accountMenu: { zIndex: '60', boxSizing: 'border-box', minWidth: '15rem', maxWidth: 'min(22rem, calc(100vw - 2rem))', overflow: 'hidden', padding: '0.375rem' },
            accountSummary: { display: 'flex', minWidth: '0', flexDirection: 'column', gap: '0.125rem', margin: '0 0 0.25rem', padding: '0.5rem 0.75rem 0.375rem' },
            accountSummaryName: { minWidth: '0', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
            accountSummaryEmail: { minWidth: '0', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', color: 'text.muted', fontSize: '0.875rem' },
            menuItem: { display: 'flex', boxSizing: 'border-box', width: '100%', alignItems: 'center', padding: '0.625rem 0.75rem', '&[data-tone="critical"]': { color: 'critical' } },
            activityTrigger: { position: 'relative', padding: '0.5rem' },
            activityPopover: { width: '24rem', maxWidth: 'calc(100vw - 2rem)', padding: '0.75rem' },
            activityBadge: { position: 'absolute', insetBlockStart: '0', insetInlineEnd: '0', minWidth: '1rem', paddingInline: '0.25rem' },
            activityHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '0.5rem' },
            activityTitle: { margin: '0', fontWeight: '600' },
            activityRefresh: { padding: '0.25rem 0.5rem' },
            activityDismiss: { padding: '0.25rem 0.5rem' },
            activityMessage: { padding: '0.5rem' },
            activityWarning: { padding: '0.5rem' },
            activityRetry: { marginTop: '0.5rem', padding: '0.25rem 0.5rem' },
            activityList: { maxHeight: '24rem', overflowY: 'auto' },
            activityRow: { display: 'flex', gap: '0.5rem', paddingBlock: '0.5rem' },
            activityItem: { minWidth: '0', flex: '1', padding: '0.25rem' },
            activitySubject: { overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
            activityMoreWrap: { marginTop: '0.5rem' },
            activityMore: { width: '100%', padding: '0.5rem 0.75rem' },
            connectionWrap: { position: 'relative', display: 'flex', alignItems: 'center', gap: '1rem' },
            connectionPopover: { zIndex: '50', width: '16rem', padding: '1rem' },
            connectionButton: { display: 'flex', alignItems: 'center', gap: '0.5rem', padding: '0.375rem 0.75rem' },
            connectionDot: { width: '0.5rem', height: '0.5rem', borderRadius: 'full', '&[data-state="connected"]': { background: 'accent.primary' }, '&[data-state="disconnected"]': { background: 'critical' } },
            connectionChevron: { width: '0.875rem', height: '0.875rem' },
            reconnectDivider: { marginTop: '1rem', paddingTop: '1rem' },
            reconnectButton: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', width: '100%', padding: '0.5rem 0.75rem' },
            icon: { width: '1.5rem', height: '1.5rem' },
            menuIcon: { width: '1.5rem', height: '1.5rem' },
            smallIcon: { width: '0.875rem', height: '0.875rem' },
            dismissIcon: { width: '0.875rem', height: '0.875rem' },
            rootInbox: { height: '100dvh', minHeight: '0', overflow: 'hidden' },
            rootStandard: { height: '100dvh', minHeight: '0', overflow: 'hidden' },
            contentInbox: { overflow: 'hidden' },
            contentStandard: { overflow: 'auto' },
            contentPadded: { padding: { base: '1rem', lg: '2rem' } },
          },
        },
        tabs: {
          className: 'tabs', slots: ['root', 'list', 'trigger', 'content', 'indicator'],
          base: { root: { display: 'flex', flexDirection: 'column', minWidth: '0' }, list: { display: 'flex', alignItems: 'center', gap: '0.25rem', borderBottom: '1px solid', borderColor: 'border.default' }, trigger: { minHeight: '2.5rem', border: '0', borderBottom: '2px solid transparent', background: 'transparent', color: 'fg.muted', padding: '0.5rem 0.75rem', fontFamily: 'primary', cursor: 'pointer', _hover: { color: 'fg.default' }, _selected: { color: 'fg.default', borderColor: 'accent.primary' }, _focusVisible: { outline: '2px solid', outlineColor: 'border.focus', outlineOffset: '2px' } }, content: { minWidth: '0', paddingBlock: '1rem' }, indicator: { display: 'none' } },
        },
        splitter: {
          className: 'splitter', slots: ['root', 'panel', 'resizeTrigger'],
          base: { root: { display: 'flex', minWidth: '0', minHeight: '0', width: '100%', height: '100%' }, panel: { minWidth: '0', minHeight: '0', overflow: 'auto' }, resizeTrigger: { flex: '0 0 0.25rem', width: '0.25rem', cursor: 'col-resize', background: 'border.default', transition: 'background 150ms ease', _hover: { background: 'border.focus' }, _focusVisible: { outline: '2px solid', outlineColor: 'border.focus', outlineOffset: '2px' } } },
        },
        scrollArea: {
          className: 'scrollArea', slots: ['root', 'viewport', 'content', 'scrollbar', 'thumb'],
          base: { root: { position: 'relative', overflow: 'hidden' }, viewport: { width: '100%', height: '100%', overflow: 'auto' }, content: { minWidth: '0' }, scrollbar: { display: 'flex', width: '0.5rem', padding: '0.125rem', background: 'bg.subtle' }, thumb: { flex: '1', borderRadius: 'full', background: 'border.default' } },
        },
        avatar: {
          className: 'avatar', slots: ['root', 'image', 'fallback'],
          base: { root: { display: 'inline-flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden', width: '2.5rem', height: '2.5rem', borderRadius: 'l2', background: 'bg.subtle', color: 'fg.default', fontFamily: 'primary', fontWeight: '600' }, image: { width: '100%', height: '100%', objectFit: 'cover' }, fallback: { display: 'flex', alignItems: 'center', justifyContent: 'center', width: '100%', height: '100%' } },
        },
        emptyState: {
          className: 'emptyState', slots: ['root', 'title', 'description', 'action'],
          base: { root: { display: 'flex', minHeight: '10rem', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', border: '1px dashed', borderColor: 'border.default', borderRadius: 'l2', background: 'bg.subtle', color: 'fg.default', padding: '1.5rem', textAlign: 'center' }, title: { margin: '0', fontFamily: 'primary', fontWeight: '600' }, description: { margin: '0', color: 'fg.muted', fontFamily: 'primary' }, action: { display: 'flex', marginTop: '0.5rem' } },
        },
        select: {
          className: 'select',
          slots: ['root', 'label', 'control', 'trigger', 'valueText', 'indicatorGroup', 'indicator', 'positioner', 'content', 'list', 'item', 'itemText', 'itemIndicator'],
          base: {
            root: { display: 'flex', flexDirection: 'column', gap: '0.375rem', width: '100%' },
            label: { color: 'text.muted', fontSize: '0.75rem', fontWeight: '600', userSelect: 'none' },
            control: { position: 'relative', display: 'flex', alignItems: 'center', width: '100%' },
            trigger: { display: 'inline-flex', alignItems: 'center', justifyContent: 'space-between', gap: '0.5rem', width: '100%', minHeight: '2.75rem', minWidth: '0', border: '1px solid', borderColor: 'border.input', borderRadius: '0.5rem', background: 'bg.input', color: 'text.primary', padding: '0.625rem 2.5rem 0.625rem 0.75rem', fontFamily: 'primary', textAlign: 'start', cursor: 'pointer', userSelect: 'none', _focusVisible: { outline: '2px solid', outlineColor: 'border.focus', outlineOffset: '2px' }, _disabled: { opacity: '0.6', cursor: 'not-allowed' } },
            valueText: { overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', _placeholderShown: { color: 'text.muted' } },
            indicatorGroup: { position: 'absolute', insetInlineEnd: '0.75rem', insetBlock: '0', display: 'flex', alignItems: 'center', justifyContent: 'center', pointerEvents: 'none' },
            indicator: { display: 'inline-flex', alignItems: 'center', justifyContent: 'center', color: 'text.muted', pointerEvents: 'none' },
            positioner: { zIndex: 70 },
            content: { minWidth: 'var(--reference-width)', maxHeight: 'min(var(--available-height), 24rem)', overflowY: 'auto', border: '1px solid', borderColor: 'border.input', borderRadius: '0.5rem', background: 'bg.surface', padding: '0.25rem', boxShadow: '0 0.75rem 1.5rem rgb(15 23 42 / 12%)' },
            list: { display: 'flex', flexDirection: 'column', gap: '0.125rem' },
            item: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '0.75rem', minHeight: '2.5rem', borderRadius: '0.375rem', padding: '0.5rem 0.625rem', color: 'text.primary', cursor: 'pointer', userSelect: 'none', _hover: { background: 'bg.subtle' }, _highlighted: { background: 'bg.subtle' }, _disabled: { opacity: '0.6', cursor: 'not-allowed' } },
            itemText: { overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
            itemIndicator: { color: 'accent.primary', display: 'inline-flex', alignItems: 'center' },
          },
        },
      },
      recipes: {
        ...parkRegistryRecipes,
        button: {
          className: 'button',
          base: { appearance: 'none', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', minHeight: '2.75rem', minWidth: '2.75rem', flexShrink: '0', isolation: 'isolate', position: 'relative', verticalAlign: 'middle', whiteSpace: 'nowrap', border: '1px solid', borderColor: 'border.input', borderRadius: 'l2', background: 'bg.surface', color: 'text.primary', padding: '0.5rem 0.875rem', fontFamily: 'primary', fontWeight: '600', cursor: 'pointer', userSelect: 'none', outline: '0', transition: 'background 150ms ease, border-color 150ms ease, color 150ms ease, box-shadow 150ms ease', _hover: { background: 'bg.subtle' }, _focusVisible: { outline: '2px solid', outlineColor: 'border.focus', outlineOffset: '2px' }, _disabled: { opacity: '0.6', cursor: 'not-allowed' }, '& svg': { flexShrink: '0' } },
          variants: {
            variant: {
              solid: { background: 'accent.primary', borderColor: 'accent.primary', color: 'bg.surface', _hover: { background: 'text.primary', borderColor: 'text.primary' } },
              subtle: { background: 'bg.subtle', borderColor: 'border.default', color: 'text.primary', _hover: { background: 'bg.input' } },
              surface: { background: 'bg.surface', borderColor: 'border.input', color: 'text.primary', _hover: { background: 'bg.subtle' } },
              outline: { background: 'transparent', borderColor: 'border.input', color: 'text.primary', _hover: { background: 'bg.subtle' } },
              plain: { background: 'transparent', borderColor: 'transparent', color: 'text.primary', _hover: { background: 'bg.subtle', borderColor: 'transparent' } },
              ghost: { background: 'transparent', borderColor: 'transparent', color: 'text.primary', _hover: { background: 'bg.subtle', borderColor: 'border.input' } },
              destructive: { background: 'critical', borderColor: 'critical', color: 'bg.surface', _hover: { filter: 'brightness(0.92)' } },
            },
            size: {
              xs: { minHeight: '2rem', minWidth: '2rem', padding: '0.375rem 0.625rem', fontSize: '0.75rem' },
              sm: { minHeight: '2.25rem', minWidth: '2.25rem', padding: '0.5rem 0.75rem', fontSize: '0.875rem' },
              md: { minHeight: '2.5rem', minWidth: '2.5rem', padding: '0.5rem 0.875rem', fontSize: '0.9375rem' },
              lg: { minHeight: '2.75rem', minWidth: '2.75rem', padding: '0.625rem 1rem', fontSize: '1rem' },
              xl: { minHeight: '3rem', minWidth: '3rem', padding: '0.75rem 1.125rem', fontSize: '1.125rem' },
              '2xl': { minHeight: '4rem', minWidth: '4rem', padding: '1rem 1.5rem', fontSize: '1.25rem' },
            },
          },
          defaultVariants: { variant: 'surface', size: 'md' },
        },
        input: {
          className: 'input',
          base: { boxSizing: 'border-box', width: '100%', minHeight: '2.75rem', border: '1px solid', borderColor: 'border.input', borderRadius: '0.5rem', background: 'bg.input', color: 'text.primary', padding: '0.625rem 0.75rem', fontFamily: 'primary', _focusVisible: { outline: '2px solid', outlineColor: 'border.focus', outlineOffset: '2px' }, _disabled: { opacity: '0.6' } },
        },
        textarea: {
          className: 'textarea',
          base: { boxSizing: 'border-box', width: '100%', minHeight: '6rem', border: '1px solid', borderColor: 'border.input', borderRadius: '0.5rem', background: 'bg.input', color: 'text.primary', padding: '0.625rem 0.75rem', fontFamily: 'primary', resize: 'vertical', _focusVisible: { outline: '2px solid', outlineColor: 'border.focus', outlineOffset: '2px' }, _disabled: { opacity: '0.6' } },
        },
        icon: {
          className: 'icon',
          base: { display: 'inline-block', flexShrink: '0', width: '1.25rem', height: '1.25rem', color: 'icon.primary', verticalAlign: 'middle' },
        },
      },
    },
  },
  staticCss: { css: [{ properties: { color: ['canvas', 'panel', 'muted', 'text', 'textMuted', 'focus', 'selected', 'divider', 'critical', 'icon.primary', 'icon.muted', 'icon.disabled', 'icon.selected', 'icon.critical', 'icon.inverse'] } }] },
};
