import { green } from './src/theme/colors/green';
import { red } from './src/theme/colors/red';
import { blue } from './src/theme/colors/blue';
import { animationStyles } from './src/theme/animation-styles';
import { zIndex } from './src/theme/tokens/z-index';
import { shadows } from './src/theme/tokens/shadows';
import { durations } from './src/theme/tokens/durations';
import { colors } from './src/theme/tokens/colors';
import { textStyles } from './src/theme/text-styles';
import { layerStyles } from './src/theme/layer-styles';
import { keyframes } from './src/theme/keyframes';
import { globalCss as parkGlobalCss } from './src/theme/global-css';
import { conditions } from './src/theme/conditions';
import { slate } from './src/theme/colors/slate';
import { absoluteCenter, badge, button, code, group, heading, icon, input, inputAddon, kbd, link, skeleton, spinner, text, textarea, accordion, alert, avatar, breadcrumb, card, carousel, checkbox, clipboard, collapsible, colorPicker, combobox, datePicker, dialog, drawer, editable, field, fieldset, fileUpload, hoverCard, inputGroup, menu, numberInput, pagination, pinInput, popover, progress, radioCardGroup, radioGroup, ratingGroup, scrollArea, segmentGroup, select, slider, splitter, switchRecipe, table, tabs, tagsInput, toast, toggleGroup, tooltip } from './src/theme/recipes/index';

const parkRegistryRecipes = { absoluteCenter: absoluteCenter, badge: badge, button: button, code: code, group: group, heading: heading, icon: icon, input: input, inputAddon: inputAddon, kbd: kbd, link: link, skeleton: skeleton, spinner: spinner, text: text, textarea: textarea };
const parkRegistrySlotRecipes = { accordion: accordion, alert: alert, avatar: avatar, breadcrumb: breadcrumb, card: card, carousel: carousel, checkbox: checkbox, clipboard: clipboard, collapsible: collapsible, colorPicker: colorPicker, combobox: combobox, datePicker: datePicker, dialog: dialog, drawer: drawer, editable: editable, field: field, fieldset: fieldset, fileUpload: fileUpload, hoverCard: hoverCard, inputGroup: inputGroup, menu: menu, numberInput: numberInput, pagination: pagination, pinInput: pinInput, popover: popover, progress: progress, radioCardGroup: radioCardGroup, radioGroup: radioGroup, ratingGroup: ratingGroup, scrollArea: scrollArea, segmentGroup: segmentGroup, select: select, slider: slider, splitter: splitter, switchRecipe: switchRecipe, table: table, tabs: tabs, tagsInput: tagsInput, toast: toast, toggleGroup: toggleGroup, tooltip: tooltip };

// The dashboard may supply validated tenant values. Portal and the widget do
// not restore operator themes, so each alias needs a usable static fallback.
const tocynColor = (name: string, light: string, dark: string) => ({
  value: {
    base: `var(--tocyn-color-${name}, ${light})`,
    _dark: `var(--tocyn-color-${name}, ${dark})`,
  },
});

/**
 * Build-time Panda configuration for the installed Park recipes.
 * Keep this file dependency-light so consumers can import the UI contract
 * without loading a styling runtime.
 */
export default {
  preflight: true,
  jsxFramework: 'react',

  globalCss: {
    ...parkGlobalCss.extend,
    'html, body, #root': { width: '100%', minHeight: '100%', margin: '0', fontFamily: 'primary', color: 'text.primary', background: 'bg.canvas' },
    '#root': { minHeight: '100dvh' },
    ':root': { colorScheme: 'light' },
    ':root[data-tocyn-font-scale="large"]': { fontSize: '112.5%' },
    ':root[data-tocyn-font-scale="larger"]': { fontSize: '125%' },
    '[data-tocyn-theme-mode="dark"], [data-tocyn-inverse]': { colorScheme: 'dark' },
    'body': { WebkitFontSmoothing: 'antialiased', MozOsxFontSmoothing: 'grayscale' },
    ':root[data-tocyn-focus-mode="true"] [data-tocyn-focus-decoration]': { display: 'none' },
    '[data-tocyn-density="compact"] main[aria-label="Workspace"]': { padding: '1rem' },
    '[data-tabular]': { fontFamily: 'tabular', fontFeatureSettings: '"tnum" 1, "cv01" 1', fontVariantNumeric: 'tabular-nums' },
    // Panda's fontFamily utility is used by metric, reference and SLA content.
    // Give every Inter instance the same numeric features as textStyles.tabular.
    '.ff_tabular': { fontFeatureSettings: '"tnum" 1, "cv01" 1', fontVariantNumeric: 'tabular-nums' },
    '.table__root': { fontFamily: 'tabular', fontFeatureSettings: '"tnum" 1, "cv01" 1', fontVariantNumeric: 'tabular-nums' },
  },

  include: ['./src/**/*.{ts,tsx}', '../../apps/dashboard/src/**/*.{ts,tsx}', '../../apps/portal/src/**/*.{ts,tsx}', '../../apps/widget/src/**/*.{ts,tsx}'],
  outdir: './src/styles/generated',

  theme: {
    extend: {
      semanticTokens: {
        colors: {
          'bg.canvas': tocynColor('surface-panel', '#fcfcfd', '#111113'),
          'bg.surface': tocynColor('surface', '#ffffff', '#111113'),
          'bg.input': tocynColor('surface-muted', '#f0f0f3', '#212225'),
          'text.primary': tocynColor('text', '#1c2024', '#edeef0'),
          'text.muted': tocynColor('text-muted', '#60646c', '#b0b4ba'),
          'border.input': tocynColor('divider', '#d9d9e0', '#363a3f'),
          'border.focus': { value: '{colors.focus}' },
          'accent.primary': { value: '{colors.gray.solid.bg}' },
          'icon.primary': { value: { _light: '{colors.gray.12}', _dark: '{colors.gray.12}' } },
          'icon.muted': { value: { _light: '{colors.gray.11}', _dark: '{colors.gray.11}' } },
          'icon.disabled': { value: { _light: '{colors.gray.9}', _dark: '{colors.gray.9}' } },
          'icon.selected': { value: { _light: '{colors.blue.11}', _dark: '{colors.blue.11}' } },
          'icon.critical': { value: { _light: '{colors.red.11}', _dark: '{colors.red.11}' } },
          'icon.inverse': { value: { _light: '{colors.gray.solid.fg}', _dark: '{colors.gray.solid.fg}' } },
          canvas: tocynColor('surface', '#ffffff', '#111113'),
          panel: tocynColor('surface-panel', '#fcfcfd', '#111113'),
          muted: tocynColor('surface-muted', '#f0f0f3', '#212225'),
          text: tocynColor('text', '#1c2024', '#edeef0'),
          textMuted: tocynColor('text-muted', '#60646c', '#b0b4ba'),
          focus: tocynColor('focus', '#1c2024', '#edeef0'),
          selected: tocynColor('selected', '#e6f4fe', '#0d2847'),
          divider: tocynColor('divider', '#d9d9e0', '#363a3f'),
          critical: tocynColor('critical', '#ce2c31', '#ff9592'),
          'critical.surface': { value: '{colors.red.2}' },
          'critical.border': { value: '{colors.red.6}' },
          warning: { value: '{colors.gray.12}' },
          'warning.surface': { value: '{colors.gray.2}' },
          'warning.border': { value: '{colors.gray.6}' },
          'info.surface': { value: '{colors.blue.2}' },
          'info.text': { value: '{colors.blue.11}' },
          inverse: tocynColor('inverse', '#1c2024', '#edeef0'),
          'bg.default': { value: '{colors.gray.1}' },
          'bg.subtle': { value: '{colors.gray.3}' },
          'fg.default': { value: '{colors.gray.12}' },
          'fg.muted': { value: '{colors.gray.11}' },
          'border.default': { value: '{colors.gray.6}' },
          gray: slate,

          fg: {
            default: {
              value: {
                _light: "{colors.gray.12}",
                _dark: "{colors.gray.12}"
              }
            },

            muted: {
              value: {
                _light: "{colors.gray.11}",
                _dark: "{colors.gray.11}"
              }
            },

            subtle: {
              value: {
                _light: "{colors.gray.11}",
                _dark: "{colors.gray.11}"
              }
            }
          },

          border: {
            value: {
              _light: "{colors.gray.4}",
              _dark: "{colors.gray.4}"
            }
          },

          error: {
            value: {
              _light: "{colors.red.9}",
              _dark: "{colors.red.9}"
            }
          },

          blue: blue,
          red: red,
          green: green
        },

        shadows: shadows
      },

      tokens: {
        fonts: {
          primary: { value: "'Atkinson Hyperlegible', sans-serif" },
          tabular: { value: "'Inter', sans-serif" },
          code: { value: "'Inter', sans-serif" },
        },

        radii: {
          l1: { value: '0.25rem' },
          l2: { value: '0.5rem' },
          l3: { value: '0.75rem' },
          control: { value: '{radii.l2}' },
          panel: { value: '{radii.l3}' },
        },

        sizes: { target: { value: 'var(--tocyn-target-min, 44px)' } },
        colors: colors,
        durations: durations,
        zIndex: zIndex
      },

      textStyles: {
        ...textStyles,
        body: { value: { fontFamily: 'primary', fontSize: '1rem', lineHeight: '1.5' } },
        tabular: { value: { fontFamily: 'tabular', fontFeatureSettings: '"tnum" 1, "cv01" 1', fontVariantNumeric: 'tabular-nums', lineHeight: '1.4' } },
      },

      slotRecipes: {
        ...parkRegistrySlotRecipes,
        page: {
          className: 'page',
          slots: [
            'root', 'header', 'content', 'grid', 'section',
            'settingsSections', 'settingsField', 'settingsError', 'settingsHelp',
            'knowledgeWorkspace', 'knowledgeSidebar', 'knowledgeContent', 'knowledgeTable', 'knowledgeRow', 'knowledgeSearch', 'knowledgePreview',
            'knowledgeCategoryRow', 'knowledgeCategoryRowSelected', 'knowledgeCategoryMain', 'knowledgeCategoryActions', 'knowledgeCategoryChildren', 'knowledgeCategoryList', 'knowledgeCategorySpacer', 'knowledgeCategoryButton', 'knowledgeDeleteActions',
            'accountGrid', 'accountIdentityName', 'accountIdentityEmail',
            'inboxWorkspace', 'inboxList', 'inboxDetail', 'inboxHeader', 'inboxHiddenHeading', 'inboxMetrics', 'inboxToolbar', 'inboxRows', 'inboxRow', 'inboxTable', 'inboxTableWrap', 'inboxTableRow', 'inboxPresentationButton', 'inboxPresentationActive', 'inboxPresentationInactive', 'inboxEmpty', 'inboxMobileHidden', 'inboxTableMobileHidden', 'inboxStatus', 'inboxPriority', 'inboxMobileNote', 'inboxTableResponsive', 'inboxTitleRow', 'inboxRowCopy', 'inboxRowSubject', 'inboxRowCustomer', 'inboxRowDate', 'inboxRowPreview', 'inboxRowMeta', 'inboxToolbarGroup', 'inboxPagination',
            'dashboardHeading', 'dashboardAction', 'metricStrip', 'metricCard', 'metricCardHeader', 'metricCardBody', 'metricIcon', 'metricLabel', 'metricValue', 'panels', 'panelHeader', 'panelIcon', 'panelTitle', 'priorityList', 'priorityRow', 'overviewGrid', 'overviewCard', 'overviewCardBody', 'overviewCardLabel', 'overviewCardValue', 'overviewFooter',
          ],
          base: {
            root: { width: '100%', minWidth: '0', minHeight: '100%', background: 'bg.canvas', color: 'text.primary', fontFamily: 'primary' },
            header: { display: 'flex', flexWrap: 'wrap', alignItems: 'flex-start', justifyContent: 'space-between', gap: '1.5rem', marginBottom: '2rem' },
            content: { width: '100%', minWidth: '0', maxWidth: '72rem', boxSizing: 'border-box', marginInline: 'auto', padding: '2rem 1rem' },
            grid: { display: 'grid', gap: '1rem', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
            section: { minWidth: '0' },
            settingsSections: { display: 'grid', gap: '1rem' },
            settingsField: { display: 'grid', gap: '0.375rem' },
            settingsError: { display: 'flex', alignItems: 'flex-start', gap: '1rem', marginBottom: '1.5rem', border: '1px solid', borderColor: 'critical.border', borderRadius: 'l2', background: 'critical.surface', color: 'critical', padding: { base: '1rem', md: '1.5rem' }, '& svg': { width: '2rem', height: '2rem', flexShrink: '0' } },
            settingsHelp: { marginTop: '0.25rem', color: 'text.muted', fontSize: '0.875rem' },
            knowledgeWorkspace: { display: 'grid', minWidth: '0', gridTemplateColumns: { base: '1fr', md: 'minmax(16rem, 20rem) minmax(0, 1fr)' }, gap: '1rem', alignItems: 'start' },
            knowledgeSidebar: { minWidth: '0', position: 'sticky', top: '1rem' },
            knowledgeContent: { minWidth: '0', overflow: 'hidden', '& .emptyState__description': { whiteSpace: 'normal', overflowWrap: 'anywhere' } },
            knowledgeTable: { width: '100%', borderCollapse: 'collapse', tableLayout: 'fixed' },
            knowledgeRow: { borderTop: '1px solid', borderColor: 'border.default', _hover: { background: 'bg.subtle' } },
            knowledgeSearch: { display: 'grid', gap: '0.5rem' },
            knowledgePreview: { display: 'grid', gap: '0.5rem', padding: '0.75rem', borderRadius: 'l2', background: 'bg.subtle' },
            knowledgeCategoryRow: { display: 'flex', minWidth: '0', alignItems: 'center', justifyContent: 'space-between', gap: '0.5rem', borderRadius: 'l2', paddingBlock: '0.25rem', paddingInlineStart: 'calc(var(--tocyn-category-depth, 0) * 1.5rem + 0.375rem)', paddingInlineEnd: '0.375rem' },
            knowledgeCategoryRowSelected: { background: 'bg.subtle', color: 'fg.default' },
            knowledgeCategoryMain: { display: 'flex', minWidth: '0', alignItems: 'center', gap: '0.25rem', flex: '1' },
            knowledgeCategoryActions: { display: 'flex', alignItems: 'center', gap: '0.25rem', flexShrink: '0' },
            knowledgeCategoryChildren: { marginInlineStart: '0.75rem', borderInlineStart: '1px solid', borderColor: 'border.default', paddingInlineStart: '0.375rem' },
            knowledgeCategoryList: { display: 'grid', gap: '0.125rem' },
            knowledgeCategorySpacer: { display: 'inline-block', width: '2.25rem', height: '2.25rem', flexShrink: '0' },
            knowledgeCategoryButton: { display: 'inline-flex', minWidth: '0', minHeight: '2.5rem', flex: '1', alignItems: 'center', justifyContent: 'flex-start', gap: '0.5rem', overflow: 'hidden', border: '0', background: 'transparent', color: 'fg.default', padding: '0.5rem', textAlign: 'start', _hover: { background: 'bg.subtle' } },
            knowledgeDeleteActions: { display: 'flex', justifyContent: 'flex-end', gap: '0.75rem', marginTop: '1rem' },
            accountGrid: { display: 'grid', minWidth: '0', gridTemplateColumns: { base: 'minmax(0, 1fr)', md: 'repeat(2, minmax(0, 1fr))' }, gap: '1rem', marginBlock: '1rem', '& > *': { minWidth: '0' } },
            accountIdentityName: { margin: '0', fontWeight: '600' },
            accountIdentityEmail: { overflow: 'hidden', margin: '0.25rem 0 0', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
            inboxWorkspace: { display: 'flex', minWidth: '0', minHeight: '0', width: '100%', height: '100%', flex: '1', '& [data-part="resize-trigger"]': { display: { base: 'none', lg: 'flex' } } },
            // Ark owns desktop panel flex ratios and bounds through inline styles.
            // Override its max-width only while a single mobile panel is visible.
            inboxList: { display: 'flex', minHeight: '0', height: '100%', minWidth: '0', flexDirection: 'column', overflow: 'hidden', width: '100%', margin: '0', padding: '0', boxSizing: 'border-box', '@media screen and (max-width: 63.999rem)': { maxWidth: 'none !important' } },
            inboxDetail: { display: 'flex', minHeight: '0', height: '100%', minWidth: '0', flexDirection: 'column', overflow: 'hidden', background: 'bg.canvas', width: '100%', margin: '0', padding: '0', boxSizing: 'border-box', '@media screen and (max-width: 63.999rem)': { maxWidth: 'none !important' } },
            inboxHeader: { display: 'grid', flexShrink: '0', gap: '0.75rem', padding: { base: '0.75rem', md: '0.875rem 1rem 0.75rem' }, borderBottom: '1px solid', borderColor: 'border.default', background: 'bg.surface', '& > p': { margin: '0', color: 'text.muted', fontSize: '0.8125rem' } },
            inboxMetrics: { display: 'grid', gridTemplateColumns: { base: 'repeat(2, minmax(0, 1fr))', lg: 'repeat(4, minmax(0, 1fr))' }, gap: '0.5rem', '& [data-part="body"]': { minWidth: '0', padding: '0.625rem 0.75rem' }, '& strong': { display: 'block', marginTop: '0.125rem', fontSize: '1.25rem' } },
            inboxHiddenHeading: { position: 'absolute', width: '1px', height: '1px', overflow: 'hidden', clip: 'rect(0 0 0 0)', clipPath: 'inset(50%)', whiteSpace: 'nowrap' },
            inboxToolbar: { display: 'flex', minWidth: '0', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: '0.5rem', padding: '0.5rem 1rem', borderBottom: '1px solid', borderColor: 'border.default', '& p': { minWidth: '0', flex: '1 1 8rem', margin: '0', overflow: 'hidden', color: 'text.muted', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontSize: '0.8125rem' } },
            inboxRows: { display: 'flex', minHeight: '0', flex: '1', flexDirection: 'column', overflowY: 'auto' },
            inboxRow: { display: 'grid', gap: '0.5rem', borderBottom: '1px solid', borderColor: 'border.default', padding: '1rem 1.5rem', _hover: { background: 'bg.subtle' }, '&[data-selected="true"]': { background: 'bg.subtle', borderInlineStart: '3px solid', borderInlineStartColor: 'border.focus' } },
            inboxTable: { width: '100%', borderCollapse: 'collapse', tableLayout: 'fixed' },
            inboxTableWrap: { width: '100%', minWidth: '0', overflowX: 'auto' },
            inboxTableRow: { borderBottom: '1px solid', borderColor: 'border.default', _hover: { background: 'bg.subtle' }, '&[data-selected="true"]': { background: 'bg.subtle' }, '& td': { padding: '0.75rem 1rem', verticalAlign: 'top' } },
            inboxPresentationButton: { display: 'inline-flex', minWidth: '2.75rem', minHeight: '2.75rem', alignItems: 'center', justifyContent: 'center', border: '1px solid', borderColor: 'border.input', borderRadius: 'l2', padding: '0.5rem', _focusVisible: { outline: '2px solid', outlineColor: 'border.focus', outlineOffset: '2px' } },
            inboxPresentationActive: { background: 'bg.subtle', color: 'text.primary' },
            inboxPresentationInactive: { background: 'bg.surface', color: 'text.muted', _hover: { background: 'bg.subtle', color: 'text.primary' } },
            inboxEmpty: { display: 'flex', minHeight: '16rem', alignItems: 'center', justifyContent: 'center', padding: '2rem' },
            inboxMobileHidden: { '&[data-part="panel"]': { display: { base: 'none !important', lg: 'flex !important' } } },
            inboxTableMobileHidden: { display: { base: 'block', md: 'none' } },
            inboxStatus: { display: 'inline-flex', minHeight: '1.75rem', alignItems: 'center', borderRadius: 'full', background: 'bg.subtle', color: 'text.muted', padding: '0.25rem 0.625rem', fontSize: '0.8125rem', fontWeight: '600', '&[data-status="open"]': { background: 'info.surface', color: 'info.text' }, '&[data-status="pending"]': { background: 'warning.surface', color: 'warning' } },
            inboxPriority: { display: 'inline-flex', alignItems: 'center', gap: '0.25rem', color: 'text.muted', textTransform: 'capitalize', '&[data-priority="normal"]': { color: 'info.text' }, '&[data-priority="high"]': { color: 'warning' }, '&[data-priority="urgent"]': { color: 'critical' } },
            inboxMobileNote: { display: { base: 'block', sm: 'none' }, color: 'text.muted', fontSize: '0.875rem' },
            inboxTableResponsive: { display: { base: 'none', sm: 'block' }, overflowX: 'auto' },
            inboxTitleRow: { display: 'flex', minWidth: '0', alignItems: 'flex-start', justifyContent: 'space-between', gap: '1rem' },
            inboxRowCopy: { display: 'grid', minWidth: '0', gap: '0.125rem' },
            inboxRowSubject: { margin: '0', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontWeight: '600' },
            inboxRowCustomer: { margin: '0', overflow: 'hidden', color: 'text.muted', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontSize: '0.875rem' },
            inboxRowDate: { flexShrink: '0', color: 'text.muted', fontSize: '0.8125rem' },
            inboxRowPreview: { margin: '0', overflow: 'hidden', color: 'text.muted', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontSize: '0.875rem' },
            inboxRowMeta: { display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: '0.5rem', color: 'text.muted', fontSize: '0.8125rem' },
            inboxToolbarGroup: { display: 'flex', minWidth: '0', alignItems: 'center', gap: '0.5rem' },
            inboxPagination: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '1rem', borderTop: '1px solid', borderColor: 'border.default', padding: '0.75rem 1.5rem' },
            dashboardHeading: { display: 'grid', minWidth: '0', flex: '1 1 auto', gap: '0.25rem', '& h1': { margin: '0', fontSize: '2rem', lineHeight: '1.15' }, '& p': { margin: '0', color: 'text.muted' } },
            dashboardAction: { flexShrink: '0' },
            metricStrip: { display: 'grid', gridTemplateColumns: { base: 'minmax(0, 1fr)', sm: 'repeat(2, minmax(0, 1fr))', lg: 'repeat(4, minmax(0, 1fr))' }, gap: '1rem' },
            metricCard: { minWidth: '0', height: '100%' },
            metricCardHeader: { '&.card__header': { flexDirection: 'row', alignItems: 'center', gap: '0.75rem', paddingBottom: '0.5rem' } },
            metricCardBody: { '&.card__body': { paddingTop: '0', justifyContent: 'flex-end' } },
            metricIcon: { display: 'inline-flex', width: '2.25rem', height: '2.25rem', flexShrink: '0', alignItems: 'center', justifyContent: 'center', borderRadius: 'l2', background: 'bg.subtle', color: 'text.primary', '& svg': { width: '1.25rem', height: '1.25rem' }, '&[data-tone="blue"]': { background: 'info.surface', color: 'info.text' }, '&[data-tone="green"]': { background: 'green.3', color: 'green.11' }, '&[data-tone="amber"]': { background: 'warning.surface', color: 'warning' }, '&[data-tone="neutral"]': { background: 'bg.input', color: 'text.muted' } },
            metricLabel: { '&.card__title': { minWidth: '0', margin: '0', fontSize: '0.875rem', fontWeight: '600', lineHeight: '1.25rem' } },
            metricValue: { margin: '0', fontSize: '2rem', fontWeight: '700', lineHeight: '1.1' },
            panels: { display: 'grid', gridTemplateColumns: { base: 'minmax(0, 1fr)', lg: 'repeat(2, minmax(0, 1fr))' }, gap: '1rem', '& > *': { minWidth: '0' } },
            panelHeader: { '&.card__header': { flexDirection: 'row', alignItems: 'center', gap: '0.75rem', paddingBottom: '1rem' } },
            panelIcon: { width: '1.25rem', height: '1.25rem', flexShrink: '0', color: 'text.muted' },
            panelTitle: { '&.card__title': { minWidth: '0', margin: '0', fontSize: '1.125rem', lineHeight: '1.5rem' } },
            priorityList: { display: 'grid', minWidth: '0', gap: '0.75rem' },
            priorityRow: { display: 'grid', minWidth: '0', gap: '0.375rem', '& > div:first-child': { display: 'flex', minWidth: '0', alignItems: 'center', justifyContent: 'space-between', gap: '1rem', textTransform: 'capitalize' } },
            overviewGrid: { display: 'grid', gridTemplateColumns: { base: 'minmax(0, 1fr)', sm: 'repeat(2, minmax(0, 1fr))' }, gap: '0.75rem' },
            overviewCard: { minWidth: '0' },
            overviewCardBody: { '&.card__body': { minWidth: '0', gap: '0.5rem', padding: '1rem' } },
            overviewCardLabel: { display: 'flex', minWidth: '0', alignItems: 'center', gap: '0.5rem', color: 'text.muted', fontSize: '0.875rem', '& svg': { width: '1rem', height: '1rem', flexShrink: '0' } },
            overviewCardValue: { margin: '0', fontSize: '1.5rem', fontWeight: '700', lineHeight: '1.25' },
            overviewFooter: { margin: '1rem 0 0', color: 'text.muted', fontSize: '0.875rem' },
          },
          variants: {
            kind: {
              dashboard: { header: { alignItems: 'center', marginBottom: '0' }, content: { maxWidth: '88rem', display: 'grid', gap: '1.5rem' } },
              knowledge: { content: { maxWidth: '96rem', display: 'grid', gap: '1.5rem', alignContent: 'start' } },
              inbox: { content: { maxWidth: 'none', padding: '0' } },
              settings: { content: { maxWidth: '56rem' } },
              account: { content: { maxWidth: '72rem' } },
            },
          },
          compoundVariants: [
            { kind: 'settings', css: { grid: { gridTemplateColumns: '1fr' }, settingsSections: { maxWidth: '56rem', marginInline: 'auto' } } },
          ],
          defaultVariants: { kind: 'dashboard' },
        },
        ticketDetail: {
          className: 'ticketDetail',
          slots: [
            'root', 'main', 'loading', 'unavailable', 'status', 'toolbar', 'back', 'controls', 'control',
            'card', 'header', 'heading', 'titleStack', 'titleRow', 'reference', 'title', 'meta', 'customer', 'opened',
            'presence', 'viewers', 'avatars', 'avatar', 'liveLabel', 'liveDot', 'typing', 'messages', 'timelineRow',
            'timelineAvatar', 'timelineBubble', 'timelineMeta', 'timelineLabel', 'timelineTime', 'timelineBody', 'emailPresentation',
            'emailSummary', 'emailSummaryIcon', 'emailSummaryLabel', 'emailSummaryTime', 'emailSummaryFields', 'emailDisclosure',
            'emailCopy', 'attachments', 'attachmentLink', 'attachmentIcon', 'attachmentName', 'attachmentSize', 'legacyMarker',
            'actions', 'actionItem', 'actionReason', 'actionStatus', 'actionNotice', 'actionMore', 'actionSummary', 'actionLink', 'slaActionBar', 'slaPanel', 'slaTitle', 'slaGrid', 'slaLabel', 'slaValue', 'slaHandler', 'slaState',
            'qa', 'qaActions', 'qaButton', 'qaButtonActive', 'qaButtonInactive', 'qaMarked', 'qaMarkedIcon', 'pagination',
            'paginationButton', 'composerPanel', 'draftActions', 'composerForm', 'modeRow', 'modeGroup',
            'modeButton', 'modeButtonActive', 'modeButtonInactive', 'suggestion', 'suggestionHeader', 'suggestionActions', 'suggestionCopy',
            'replyCapability', 'mentions', 'mentionList', 'mentionOption', 'composerAttachments', 'composerAttachment', 'composerFooter',
            'composerNote', 'composerActions', 'contextPanel', 'contextCard', 'contextSummary', 'contextBody', 'contextSettingsCard',
            'contextSettingsFields', 'contextField', 'contextFieldLabel', 'contextFieldControl', 'contextHistory', 'contextHistoryItem',
            'supportStateForm', 'supportStateHeader', 'supportStateFields', 'supportStateActions', 'supportStateHelp', 'supportStateNotice',
          ],
          base: {
            root: { display: 'grid', minWidth: '0', minHeight: '0', width: '100%', height: '100%', gridTemplateColumns: { base: 'minmax(0, 1fr)', lg: 'minmax(0, 1fr) minmax(16rem, 22rem)' }, overflow: 'visible', background: 'bg.canvas', color: 'text.primary', fontFamily: 'primary', '&[data-panel="conversation"]': { gridTemplateColumns: 'minmax(0, 1fr)' } },
            main: { display: 'flex', minWidth: '0', minHeight: '0', minInlineSize: '0', flexDirection: 'column', gap: '0.5rem', overflowX: 'hidden', overflowY: 'auto', padding: { base: '0.5rem', md: '0.75rem' } },
            loading: { display: 'grid', minHeight: '12rem', placeItems: 'center', color: 'text.muted', fontFamily: 'primary' },
            unavailable: { display: 'grid', minHeight: '16rem', placeItems: 'center', padding: '2rem' },
            status: { margin: '0', color: 'text.muted', fontSize: '0.875rem' },
            toolbar: { display: 'flex', minWidth: '0', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: '0.75rem', border: '1px solid', borderColor: 'border.default', borderRadius: 'l2', background: 'bg.surface', padding: '0.5rem 0.75rem' },
            back: { display: 'inline-flex', minHeight: '2.75rem', flexShrink: '0', alignItems: 'center', gap: '0.5rem', borderRadius: 'l2', color: 'text.primary', padding: '0.5rem 0.75rem', textDecoration: 'none', _hover: { background: 'bg.subtle' }, _focusVisible: { outline: '2px solid', outlineColor: 'border.focus', outlineOffset: '2px' } },
            controls: { display: 'flex', minWidth: '0', maxWidth: '100%', flexWrap: 'wrap', alignItems: 'center', gap: '0.5rem' },
            control: { minWidth: '8rem', maxWidth: '100%', flex: '1 1 9rem' },
            actions: { display: 'flex', minWidth: '0', flexWrap: 'wrap', alignItems: 'center', gap: '0.5rem', border: '1px solid', borderColor: 'border.default', borderRadius: 'l2', background: 'bg.surface', padding: '0.5rem 0.75rem' },
            actionItem: { display: 'grid', minWidth: '0', gap: '0.25rem' },
            actionReason: { margin: '0', color: 'text.muted', fontSize: '0.8125rem' },
            actionStatus: { margin: '0', color: 'text.muted', fontSize: '0.875rem' },
            actionNotice: { margin: '0', color: 'text.muted', fontSize: '0.875rem' },
            actionMore: { display: 'flex', minWidth: '0', flexWrap: 'wrap', gap: '0.5rem', marginBlockStart: '0.5rem' },
            actionSummary: { display: 'inline-flex', minHeight: '2.5rem', alignItems: 'center', borderRadius: 'l2', color: 'text.primary', cursor: 'pointer', padding: '0.5rem 0.75rem', _hover: { background: 'bg.subtle' }, _focusVisible: { outline: '2px solid', outlineColor: 'border.focus', outlineOffset: '2px' } },
            actionLink: { display: 'inline-flex', minHeight: '2.75rem', alignItems: 'center', justifyContent: 'center', border: '1px solid', borderColor: 'border.input', borderRadius: 'l2', background: 'bg.surface', color: 'text.primary', padding: '0.5rem 0.875rem', fontWeight: '600', textDecoration: 'none', _hover: { background: 'bg.subtle' }, _focusVisible: { outline: '2px solid', outlineColor: 'border.focus', outlineOffset: '2px' } },
            slaActionBar: { display: 'flex', minWidth: '0', flexWrap: 'wrap', gap: '0.75rem', color: 'text.muted', fontSize: '0.8125rem', paddingInline: '0.25rem' },
            slaPanel: { display: 'grid', minWidth: '0', gap: '0.75rem', border: '1px solid', borderColor: 'border.default', borderRadius: 'l2', background: 'bg.subtle', padding: '0.75rem 1rem' },
            slaTitle: { margin: '0', color: 'text.primary', fontSize: '0.875rem', fontWeight: '700' },
            slaGrid: { display: 'grid', gridTemplateColumns: { base: '1fr', sm: 'repeat(2, minmax(0, 1fr))' }, gap: '0.75rem', margin: '0' },
            slaLabel: { margin: '0', color: 'text.muted', fontSize: '0.75rem' },
            slaValue: { margin: '0.25rem 0 0', color: 'text.primary', fontFamily: 'tabular', fontFeatureSettings: '"tnum" 1, "cv01" 1', '&[data-state="breached"]': { color: 'critical' }, '&[data-state="on-track"]': { color: 'info.text' }, '&[data-state="unavailable"]': { color: 'text.muted' } },
            slaHandler: { margin: '0', color: 'text.muted', fontSize: '0.8125rem' },
            slaState: { display: 'inline-flex', alignItems: 'center', minHeight: '2rem', color: 'text.muted', fontSize: '0.8125rem' },
            card: { display: 'flex', minWidth: '0', minHeight: '0', flex: '1 1 auto', flexDirection: 'column', overflow: 'hidden', border: '1px solid', borderColor: 'border.default', borderRadius: 'l3', background: 'bg.surface', boxShadow: 'xs' },
            header: { display: 'flex', minWidth: '0', flexWrap: 'wrap', alignItems: 'flex-start', justifyContent: 'space-between', gap: '1rem', borderBottom: '1px solid', borderColor: 'border.default', padding: '1rem 1.25rem' },
            heading: { display: 'flex', minWidth: '0', flex: '1', alignItems: 'flex-start', justifyContent: 'space-between', gap: '1rem' },
            titleStack: { display: 'grid', minWidth: '0', gap: '0.5rem' },
            titleRow: { display: 'flex', minWidth: '0', flexDirection: { base: 'column', sm: 'row' }, alignItems: { base: 'flex-start', sm: 'baseline' }, gap: { base: '0.25rem', sm: '0.75rem' } },
            reference: { flexShrink: '0', color: 'text.muted', fontFamily: 'tabular', fontSize: '0.875rem' },
            title: { minWidth: '0', margin: '0', overflow: 'hidden', color: 'text.primary', fontSize: '1.25rem', fontWeight: '700', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
            meta: { display: 'flex', minWidth: '0', flexWrap: 'wrap', alignItems: 'center', gap: '0.75rem', color: 'text.muted', fontSize: '0.875rem' },
            customer: { display: 'inline-flex', minWidth: '0', maxWidth: '24rem', alignItems: 'center', gap: '0.375rem', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
            opened: { display: 'inline-flex', alignItems: 'center', gap: '0.375rem' },
            presence: { display: 'grid', minWidth: '0', justifyItems: 'end', gap: '0.375rem' },
            viewers: { display: 'flex', alignItems: 'center', gap: '0.5rem' },
            avatars: { display: 'flex', alignItems: 'center' },
            avatar: { display: 'grid', width: '2rem', height: '2rem', marginInlineStart: '-0.375rem', placeItems: 'center', border: '2px solid', borderColor: 'bg.surface', borderRadius: 'full', background: 'bg.subtle', color: 'text.primary', fontSize: '0.75rem', fontWeight: '700', '&:first-child': { marginInlineStart: '0' } },
            liveLabel: { display: 'inline-flex', alignItems: 'center', gap: '0.375rem', color: 'text.muted', fontSize: '0.75rem' },
            liveDot: { width: '0.5rem', height: '0.5rem', borderRadius: 'full', background: 'accent.primary' },
            typing: { margin: '0', color: 'text.muted', fontSize: '0.875rem' },
            messages: { display: 'flex', minWidth: '0', minHeight: '0', flex: '1', flexDirection: 'column', gap: '1rem', overflowY: 'auto', padding: { base: '1rem', md: '1.25rem' }, background: 'bg.canvas' },
            timelineRow: { display: 'grid', minWidth: '0', gridTemplateColumns: '2.5rem minmax(0, 1fr)', alignItems: 'start', gap: '0.75rem' },
            timelineAvatar: { display: 'grid', width: '2.5rem', height: '2.5rem', placeItems: 'center', borderRadius: 'full', background: 'bg.subtle', color: 'text.primary', fontSize: '0.8125rem', fontWeight: '700', '&[data-sender="agent"]': { background: 'info.surface', color: 'info.text' }, '&[data-internal="true"]': { background: 'warning.surface', color: 'warning' } },
            timelineBubble: { minWidth: '0', border: '1px solid', borderColor: 'border.default', borderRadius: 'l2', background: 'bg.surface', padding: '1rem', '&[data-sender="agent"]': { background: 'bg.surface' }, '&[data-internal="true"]': { borderColor: 'warning.border', background: 'warning.surface' } },
            timelineMeta: { display: 'flex', flexWrap: 'wrap', alignItems: 'baseline', justifyContent: 'space-between', gap: '0.75rem', marginBottom: '0.75rem', color: 'text.muted', fontSize: '0.8125rem' },
            timelineLabel: { color: 'text.primary', fontWeight: '700' },
            timelineTime: { fontFamily: 'tabular', whiteSpace: 'nowrap' },
            timelineBody: { minWidth: '0', overflowWrap: 'anywhere', color: 'text.primary', fontFamily: 'primary', lineHeight: '1.6', '& p:first-child': { marginTop: '0' }, '& p:last-child': { marginBottom: '0' } },
            emailPresentation: { display: 'grid', gap: '0.75rem', marginBottom: '0.875rem', border: '1px solid', borderColor: 'border.default', borderRadius: 'l2', background: 'bg.input', padding: '0.75rem' },
            emailSummary: { display: 'flex', minWidth: '0', alignItems: 'center', gap: '0.5rem' },
            emailSummaryIcon: { flexShrink: '0', color: 'icon.primary' },
            emailSummaryLabel: { fontWeight: '700' },
            emailSummaryTime: { marginInlineStart: 'auto', color: 'text.muted', fontFamily: 'tabular', fontSize: '0.8125rem' },
            emailSummaryFields: { display: 'grid', minWidth: '0', gap: '0.25rem', margin: '0', color: 'text.muted', fontSize: '0.875rem', '& > div': { display: 'grid', gridTemplateColumns: '3rem minmax(0, 1fr)', gap: '0.5rem' }, '& dt': { fontWeight: '600' }, '& dd': { minWidth: '0', margin: '0', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' } },
            emailDisclosure: { marginTop: '0.75rem', color: 'text.muted', fontSize: '0.875rem', '& summary': { cursor: 'pointer', color: 'text.primary', fontWeight: '600' } },
            emailCopy: { display: 'grid', gap: '0.25rem', paddingTop: '0.5rem' },
            attachments: { display: 'flex', flexWrap: 'wrap', gap: '0.5rem', marginTop: '1rem' },
            attachmentLink: { display: 'inline-flex', minWidth: '0', maxWidth: '100%', alignItems: 'center', gap: '0.5rem', border: '1px solid', borderColor: 'border.input', borderRadius: 'l2', background: 'bg.input', color: 'text.primary', padding: '0.5rem 0.625rem', textAlign: 'start', _hover: { background: 'bg.subtle' }, _focusVisible: { outline: '2px solid', outlineColor: 'border.focus', outlineOffset: '2px' } },
            attachmentIcon: { flexShrink: '0' },
            attachmentName: { minWidth: '0', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
            attachmentSize: { flexShrink: '0', color: 'text.muted', fontFamily: 'tabular', fontSize: '0.75rem' },
            legacyMarker: { margin: '0.75rem 0 0', color: 'warning', fontSize: '0.8125rem' },
            qa: { display: 'flex', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: '0.75rem', marginTop: '1rem', paddingTop: '0.75rem', borderTop: '1px solid', borderColor: 'border.default' },
            qaActions: { display: 'flex', flexWrap: 'wrap', gap: '0.5rem' },
            qaButton: { minHeight: '2.5rem', paddingInline: '0.75rem' },
            qaButtonActive: { background: 'bg.subtle', color: 'text.primary' },
            qaButtonInactive: { background: 'bg.surface', color: 'text.muted' },
            qaMarked: { display: 'inline-flex', alignItems: 'center', gap: '0.375rem', color: 'text.muted', fontSize: '0.8125rem' },
            qaMarkedIcon: { flexShrink: '0' },
            pagination: { display: 'flex', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: '0.75rem', borderTop: '1px solid', borderColor: 'border.default', background: 'bg.surface', padding: '0.75rem 1rem' },
            paginationButton: { minHeight: '2.5rem' },
            composerPanel: { flexShrink: '0', borderTop: '1px solid', borderColor: 'border.default', background: 'bg.surface', padding: { base: '1rem', md: '1.25rem' } },
            draftActions: { display: 'flex', flexWrap: 'wrap', gap: '0.5rem' },
            composerForm: { display: 'grid', minWidth: '0', gap: '0.875rem' },
            modeRow: { display: 'flex', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: '0.75rem' },
            modeGroup: { display: 'flex', flexWrap: 'wrap', gap: '0.5rem' },
            modeButton: { minHeight: '2.5rem' },
            modeButtonActive: { background: 'bg.subtle', color: 'text.primary' },
            modeButtonInactive: { background: 'bg.surface', color: 'text.muted' },
            suggestion: { display: 'grid', gap: '0.75rem', border: '1px solid', borderColor: 'border.default', borderRadius: 'l2', background: 'bg.subtle', padding: '0.75rem' },
            suggestionHeader: { display: 'flex', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: '0.75rem' },
            suggestionActions: { display: 'flex', flexWrap: 'wrap', gap: '0.5rem' },
            suggestionCopy: { margin: '0', color: 'text.muted', whiteSpace: 'pre-wrap' },
            replyCapability: { margin: '0', color: 'text.muted', fontSize: '0.875rem' },
            mentions: { display: 'grid', gap: '0.75rem', border: '1px solid', borderColor: 'border.default', borderRadius: 'l2', padding: '0.75rem' },
            mentionList: { display: 'grid', gap: '0.5rem' },
            mentionOption: { display: 'flex', alignItems: 'center', gap: '0.5rem' },
            composerAttachments: { display: 'flex', flexWrap: 'wrap', gap: '0.5rem' },
            composerAttachment: { display: 'flex', minWidth: '0', maxWidth: '100%', alignItems: 'center', gap: '0.5rem', border: '1px solid', borderColor: 'border.default', borderRadius: 'l2', background: 'bg.subtle', padding: '0.5rem 0.625rem' },
            composerFooter: { display: 'flex', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: '0.75rem' },
            composerNote: { display: 'flex', minWidth: '0', alignItems: 'center', gap: '0.5rem', margin: '0', color: 'text.muted', fontSize: '0.875rem' },
            composerActions: { display: 'flex', alignItems: 'center', gap: '0.5rem' },
            contextPanel: { minWidth: '0', minHeight: '0', overflowY: 'auto', borderInlineStart: '1px solid', borderColor: 'border.default', background: 'bg.surface', padding: '1rem' },
            contextCard: { display: 'grid', gap: '1rem', border: '1px solid', borderColor: 'border.default', borderRadius: 'l2', background: 'bg.surface', padding: '1rem' },
            contextSummary: { cursor: 'pointer', color: 'text.primary', fontWeight: '700' },
            contextBody: { display: 'grid', gap: '1rem' },
            contextSettingsCard: { display: 'grid', gap: '1rem', marginTop: '1rem', border: '1px solid', borderColor: 'border.default', borderRadius: 'l2', background: 'bg.surface', padding: '1rem' },
            contextSettingsFields: { display: 'grid', gap: '1rem' },
            contextField: { display: 'grid', minWidth: '0', gap: '0.375rem' },
            contextFieldLabel: { color: 'text.primary', fontWeight: '600' },
            contextFieldControl: { minWidth: '0' },
            supportStateForm: { display: 'grid', minWidth: '0', gap: '1rem', margin: '0 1rem 1rem', border: '1px solid', borderColor: 'border.default', borderRadius: 'l2', background: 'bg.surface', padding: '1rem' },
            supportStateHeader: { display: 'grid', gap: '0.25rem' },
            supportStateFields: { display: 'grid', gridTemplateColumns: { base: '1fr', md: 'repeat(2, minmax(0, 1fr))' }, gap: '0.75rem' },
            supportStateActions: { display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: '0.5rem' },
            supportStateHelp: { margin: '0', color: 'text.muted', fontSize: '0.875rem' },
            supportStateNotice: { margin: '0', color: 'text.muted', fontSize: '0.875rem' },
            contextHistory: { display: 'grid', gap: '0.75rem', margin: '0', padding: '0', listStyle: 'none' },
            contextHistoryItem: { borderTop: '1px solid', borderColor: 'border.default', paddingTop: '0.75rem' },
          },
        },
        globalSearch: {
          className: 'globalSearch',
          slots: ['root', 'inputShell', 'icon', 'input', 'shortcut', 'divider', 'scope', 'clear', 'popover', 'status', 'results', 'result', 'preview'],
          base: {
            root: { position: 'relative', display: 'flex', flexWrap: { base: 'wrap', md: 'nowrap' }, flex: '1', minWidth: { base: 'min(18rem, 100%)', md: '24rem' }, width: '100%', maxWidth: '36rem', marginInline: 'auto', alignItems: 'center', border: '1px solid', borderColor: 'border.input', borderRadius: 'l2', background: 'bg.input', color: 'text.primary', '&:has(.globalSearch__input:is(:focus-visible, [data-focus-visible]))': { outlineWidth: 'var(--focus-ring-width, 2px)', outlineStyle: 'solid', outlineColor: 'var(--global-color-focus-ring, #005FCC)', outlineOffset: '2px' } },
            inputShell: { position: 'relative', display: 'flex', flex: { base: '1 1 100%', md: '1 1 0%' }, minWidth: '0', alignItems: 'center' },
            icon: { position: 'static', flexShrink: '0', width: '1rem', height: '1rem', marginInlineStart: '0.75rem', color: 'icon.muted', pointerEvents: 'none' },
            // Park's input variant outranks the slot base layer; the composite owns this focus ring.
            input: { flex: '1', width: '0', minWidth: '0', minHeight: '2.75rem', border: '0', borderRadius: 'l2', background: 'transparent', paddingInline: '0.5rem', outline: '0', '--focus-ring-width': '0px' },
            shortcut: { position: 'static', flexShrink: '0', marginInlineEnd: '0.75rem', color: 'text.muted', fontSize: '0.75rem', pointerEvents: 'none', whiteSpace: 'nowrap' },
            divider: { display: { base: 'none', md: 'block' }, width: '1px', height: '1.5rem', flexShrink: '0', background: 'border.input' },
            scope: { display: 'flex', flexShrink: '0', width: { base: '100%', md: '9rem' }, minWidth: '0', alignItems: 'stretch' },
            clear: { position: 'static', flexShrink: '0', minWidth: '2.5rem', minHeight: '2.5rem', paddingInline: '0.5rem', color: 'text.muted', background: 'transparent', _hover: { background: 'bg.subtle', color: 'text.primary' } },
            popover: { position: 'absolute', insetBlockStart: 'calc(100% + 0.5rem)', insetInline: '0', zIndex: '50', maxHeight: 'min(24rem, 60vh)', overflowY: 'auto', border: '1px solid', borderColor: 'border.input', borderRadius: 'l2', background: 'bg.surface', color: 'text.primary', padding: '0.75rem', boxShadow: 'sm' },
            status: { color: 'text.muted', fontSize: '0.875rem' },
            results: { maxHeight: '16rem', overflow: 'auto', display: 'flex', flexDirection: 'column', gap: '0.125rem' },
            result: { display: 'flex', width: '100%', minHeight: '2.5rem', alignItems: 'center', border: '0', borderRadius: 'l2', background: 'transparent', color: 'text.primary', padding: '0.5rem 0.75rem', textAlign: 'start', textDecoration: 'none', _hover: { background: 'bg.subtle' }, _focusVisible: { outline: '2px solid', outlineColor: 'border.focus', outlineOffset: '2px' } },
            preview: { border: '1px solid', borderColor: 'border.default', borderRadius: 'l2', background: 'bg.subtle', color: 'text.primary', padding: '0.75rem' },
          },
        },
        settingsLayout: {
          className: 'settingsLayout',
          slots: ['root', 'sidebar', 'sidebarInner', 'title', 'nav', 'navLink', 'navIcon', 'sectionTitle', 'main', 'content'],
          base: {
            root: { display: 'grid', minWidth: '0', minHeight: '0', width: '100%', gridTemplateColumns: { base: '1fr', md: '16rem minmax(0, 1fr)' }, background: 'bg.canvas' },
            sidebar: { minWidth: '0', borderBottom: { base: '1px solid', md: '0' }, borderRight: { md: '1px solid' }, borderColor: 'border.default', background: 'bg.surface' },
            sidebarInner: { position: { md: 'sticky' }, top: { md: '0' }, display: 'grid', gap: '0.75rem', padding: '1.25rem 1rem' },
            title: { margin: '0', color: 'text.primary', fontSize: '1.125rem', fontWeight: '700' },
            nav: { display: 'grid', gap: '0.25rem' },
            navLink: { display: 'flex', minHeight: '2.75rem', minWidth: '0', alignItems: 'center', gap: '0.75rem', borderRadius: 'l2', color: 'text.muted', padding: '0.5rem 0.75rem', textDecoration: 'none', transition: 'colors', _hover: { background: 'bg.subtle', color: 'text.primary' }, _focusVisible: { outline: '2px solid', outlineColor: 'border.focus', outlineOffset: '2px' }, '&[aria-current="page"]': { background: 'bg.subtle', color: 'text.primary', fontWeight: '600' } },
            navIcon: { flexShrink: '0', width: '1.25rem', height: '1.25rem', color: 'currentColor' },
            sectionTitle: { margin: '0.75rem 0 0', color: 'text.muted', fontSize: '0.75rem', fontWeight: '700', letterSpacing: '0.08em', textTransform: 'uppercase' },
            main: { minWidth: '0', minHeight: '0' },
            content: { width: '100%', minWidth: '0', maxWidth: '72rem', boxSizing: 'border-box', marginInline: 'auto', padding: { base: '1.25rem 1rem', md: '2rem 1.5rem' } },
          },
        },
        knowledgeEditor: {
          className: 'knowledgeEditor',
          slots: ['root', 'header', 'heading', 'back', 'title', 'save', 'spinner', 'content', 'stack', 'error', 'card', 'fields', 'field', 'control', 'tiptap'],
          base: {
            root: { display: 'grid', minWidth: '0', gap: '1.5rem' },
            header: { display: 'flex', minWidth: '0', alignItems: 'center', justifyContent: 'space-between', gap: '1rem', borderBottom: '1px solid', borderColor: 'border.default', paddingBottom: '1rem' },
            heading: { display: 'flex', minWidth: '0', alignItems: 'center', gap: '0.75rem' },
            back: { flexShrink: '0', width: '2.75rem', height: '2.75rem', padding: '0' },
            title: { minWidth: '0', margin: '0', overflow: { base: 'visible', md: 'hidden' }, color: 'text.primary', fontSize: '1.5rem', fontWeight: '700', lineHeight: 'shorter', textOverflow: { base: 'clip', md: 'ellipsis' }, whiteSpace: { base: 'normal', md: 'nowrap' } },
            save: { flexShrink: '0' },
            spinner: { animation: 'spin 1s linear infinite' },
            content: { width: '100%' },
            stack: { display: 'grid', maxWidth: '72rem', marginInline: 'auto', gap: '1rem' },
            error: { width: '100%' },
            card: { display: 'grid', gap: '1.5rem', border: '1px solid', borderColor: 'border.default', borderRadius: 'panel', background: 'bg.surface', padding: { base: '1rem', md: '1.5rem' } },
            fields: { display: 'grid', gridTemplateColumns: { base: '1fr', md: 'minmax(0, 2fr) minmax(0, 1fr) minmax(0, 1fr)' }, gap: '1rem' },
            field: { display: 'grid', minWidth: '0', gap: '0.375rem' },
            control: { width: '100%' },
            tiptap: { minWidth: '0' },
          },
        },
        composer: {
          className: 'composer',
          slots: ['root', 'formatHelp', 'markdown', 'toolbar', 'toolbarButton', 'input', 'editor', 'autocomplete', 'autocompleteOption', 'dropHelp', 'preview', 'previewSummary', 'previewBody'],
          base: {
            root: { position: 'relative', display: 'grid', minWidth: '0', gap: '0.75rem' },
            formatHelp: { margin: '0', color: 'text.muted', fontSize: '0.875rem' },
            markdown: { display: 'grid', minWidth: '0', overflow: 'hidden', border: '1px solid', borderColor: 'border.input', borderRadius: 'l2', background: 'bg.input' },
            toolbar: { display: 'flex', flexWrap: 'wrap', gap: '0.25rem', borderBottom: '1px solid', borderColor: 'border.input', background: 'bg.surface', padding: '0.375rem' },
            toolbarButton: { minWidth: '2.5rem', minHeight: '2.5rem', padding: '0.5rem' },
            input: { minHeight: '12rem', resize: 'vertical' },
            editor: { minHeight: '12rem', padding: '1rem', bg: 'bg.input', color: 'text.primary', fontFamily: 'primary', lineHeight: '1.5', '& .ProseMirror': { minHeight: '10rem', bg: 'bg.input', color: 'text.primary', fontFamily: 'primary', overflowWrap: 'anywhere', _focusVisible: { outline: '2px solid', outlineColor: 'border.focus', outlineOffset: '2px' } }, '& .ProseMirror code': { fontFamily: 'tabular', fontFeatureSettings: '"tnum" 1, "cv01" 1', fontVariantNumeric: 'tabular-nums' } },
            autocomplete: { position: 'absolute', zIndex: '10', maxWidth: '24rem', maxHeight: '15rem', overflowY: 'auto', border: '1px solid', borderColor: 'border.default', borderRadius: 'l2', background: 'bg.surface', padding: '0.25rem', boxShadow: 'sm' },
            autocompleteOption: { display: 'flex', width: '100%', minHeight: '2.5rem', alignItems: 'center', borderRadius: 'l2', padding: '0.5rem 0.75rem', textAlign: 'start', _hover: { background: 'bg.subtle' } },
            dropHelp: { margin: '0', color: 'text.muted', fontSize: '0.875rem' },
            preview: { border: '1px solid', borderColor: 'border.default', borderRadius: 'l2', background: 'bg.subtle', padding: '0.75rem' },
            previewSummary: { cursor: 'pointer', color: 'text.muted', fontWeight: '600' },
            previewBody: { marginTop: '0.75rem', whiteSpace: 'pre-wrap', fontFamily: 'primary' },
          },
        },
        ticketFields: {
          className: 'ticketFields',
          slots: ['page', 'header', 'title', 'description', 'create', 'createIcon', 'tableShell', 'table', 'tableHead', 'tableRow', 'fieldType', 'fieldStatus', 'fieldStatusActive', 'fieldStatusInactive', 'dialog', 'dialogHeader', 'dialogTitle', 'dialogClose', 'dialogCloseIcon', 'dialogForm', 'dialogError', 'dialogFields', 'dialogLabel', 'dialogControl', 'dialogHelp', 'optionsReveal', 'checkbox', 'dialogActions', 'dialogCancel', 'dialogSubmit'],
          base: {
            page: { display: 'grid', maxWidth: '72rem', width: '100%', marginInline: 'auto', gap: '1.5rem' },
            header: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '1.5rem' },
            title: { margin: '0', color: 'text.primary', fontSize: '1.5rem', fontWeight: '700' },
            description: { margin: '0.25rem 0 0', color: 'text.muted' },
            create: { display: 'inline-flex', alignItems: 'center', gap: '0.5rem' },
            createIcon: { width: '1rem', height: '1rem' },
            tableShell: { overflow: 'hidden', border: '1px solid', borderColor: 'border.default', borderRadius: 'panel', background: 'bg.surface' },
            table: { width: '100%', borderCollapse: 'collapse', tableLayout: 'fixed' },
            tableHead: { background: 'bg.subtle', color: 'text.muted', textAlign: 'start', fontSize: '0.8125rem', textTransform: 'uppercase' },
            tableRow: { borderTop: '1px solid', borderColor: 'border.default', _hover: { background: 'bg.subtle' }, '& td, & th': { padding: '0.75rem 1rem', textAlign: 'start', verticalAlign: 'top' } },
            fieldType: { display: 'inline-flex', alignItems: 'center', gap: '0.5rem' },
            fieldStatus: { display: 'inline-flex', minHeight: '1.75rem', alignItems: 'center', borderRadius: 'full', padding: '0.25rem 0.625rem', fontSize: '0.8125rem', fontWeight: '600' },
            fieldStatusActive: { background: 'info.surface', color: 'info.text' },
            fieldStatusInactive: { background: 'bg.subtle', color: 'text.muted' },
            dialog: { width: '100%', maxWidth: '32rem', padding: '1.5rem' },
            dialogHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '1rem' },
            dialogTitle: { margin: '0', color: 'text.primary', fontSize: '1.25rem' },
            dialogClose: { minWidth: '2.75rem', minHeight: '2.75rem', padding: '0' },
            dialogCloseIcon: { width: '1.25rem', height: '1.25rem' },
            dialogForm: { display: 'grid', gap: '1rem', marginTop: '1rem' },
            dialogError: { margin: '0', border: '1px solid', borderColor: 'critical.border', borderRadius: 'l2', background: 'critical.surface', color: 'critical', padding: '0.75rem' },
            dialogFields: { display: 'grid', gap: '1rem', border: '0', padding: '0' },
            dialogLabel: { display: 'block', marginBottom: '0.375rem', color: 'text.primary', fontWeight: '600' },
            dialogControl: { width: '100%' },
            dialogHelp: { margin: '0.25rem 0 0', color: 'text.muted', fontSize: '0.875rem' },
            optionsReveal: { display: 'grid' },
            checkbox: { display: 'flex', alignItems: 'center', gap: '0.5rem' },
            dialogActions: { display: 'flex', justifyContent: 'flex-end', gap: '0.75rem', paddingTop: '0.5rem' },
            dialogCancel: {},
            dialogSubmit: {},
          },
        },
        shell: {
          className: 'shell',
          slots: ['root', 'body', 'sidebar', 'sidebarFooter', 'settingsNavigation', 'sidebarPersonaHost', 'headerPersonaHost', 'headerSearch', 'main', 'header', 'pageTitle', 'content', 'navigation', 'navigationLink', 'navigationLinkLabelled', 'navigationLinkIcon', 'navigationIcon', 'sidebarDesktop', 'sidebarLabelled', 'sidebarCompact', 'logoLink', 'logo', 'mobileDialog', 'mobileDialogLabelled', 'mobileDialogCompact', 'mobileContent', 'mobileClose', 'mobileTrigger', 'personaTrigger', 'personaTriggerLabelled', 'personaAvatar', 'personaStatus', 'personaDetails', 'personaName', 'personaPresence', 'accountMenu', 'accountSummary', 'accountSummaryName', 'accountSummaryEmail', 'menuItem', 'activityTrigger', 'activityPopover', 'activityBadge', 'activityHeader', 'activityTitle', 'activityRefresh', 'activityDismiss', 'activityLoading', 'activityEmpty', 'activityScroll', 'activityList', 'activityRow', 'activityItem', 'activitySubject', 'activityMoreWrap', 'activityMore', 'connectionWrap', 'connectionPopover', 'connectionButton', 'connectionLabel', 'connectionDot', 'connectionChevron', 'reconnectDivider', 'reconnectButton', 'icon', 'menuIcon', 'smallIcon', 'dismissIcon', 'rootInbox', 'rootStandard', 'contentInbox', 'contentStandard', 'contentPadded'],
          base: {
            root: { display: 'flex', width: '100%', minHeight: '100dvh', flexDirection: 'column', overflow: 'hidden', background: 'bg.canvas', color: 'text.primary', fontFamily: 'primary' },
            body: { display: 'flex', flex: '1', minWidth: '0', minHeight: '0', overflow: 'hidden' },
            sidebar: { display: 'flex', boxSizing: 'border-box', height: '100%', flexDirection: 'column', flexShrink: '0', width: '4rem', minHeight: '100%', background: 'bg.default', color: 'fg.default', borderRight: '1px solid', borderColor: 'border.default', padding: '1rem 0.5rem' },
            main: { display: 'flex', flex: '1', minWidth: '0', minHeight: '0', flexDirection: 'column', background: 'bg.canvas' },
            header: { display: 'flex', flexWrap: 'wrap', flexShrink: '0', minHeight: '4rem', alignItems: 'center', gap: '0.5rem 1rem', borderBottom: '1px solid', borderColor: 'border.default', background: 'bg.surface', padding: '0.5rem 1rem' },
            headerSearch: { display: 'flex', order: { base: '1', md: '0' }, flex: { base: '0 0 100%', md: '1' }, minWidth: '0', maxWidth: { base: '100%', md: '36rem' }, marginInline: { md: 'auto' }, '& > .globalSearch__root': { minWidth: { md: '0' } }, '@media (min-width: 48rem) and (max-width: 55.99rem)': { '&.shell__headerSearch': { order: '1', flex: '0 0 100%', maxWidth: '100%' } } },
            pageTitle: { display: { base: 'none', md: 'block' }, minWidth: '0', maxWidth: { base: '8rem', sm: '14rem', lg: '18rem' }, flexShrink: '0', margin: '0', overflow: 'hidden', color: 'text.primary', fontSize: '1rem', fontWeight: '700', lineHeight: '1.25', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
            content: { display: 'flex', flex: '1', minWidth: '0', minHeight: '0', flexDirection: 'column', '&:focus': { outline: 'none' } },
            navigation: { display: 'flex', flex: '1', width: '100%', flexDirection: 'column', alignItems: 'center', gap: '0.5rem', marginTop: '1.5rem' },
            sidebarFooter: { display: 'flex', flexDirection: 'column', alignItems: 'center', width: '100%', gap: '0.5rem', borderTop: '1px solid', borderColor: 'border.default', paddingTop: '0.75rem' },
            settingsNavigation: { display: 'flex', width: '100%', justifyContent: 'center' },
            sidebarPersonaHost: { display: 'flex', minWidth: '0', width: '100%', minHeight: '2.75rem', alignItems: 'center', justifyContent: 'center', '& > div': { display: 'flex', width: '100%', justifyContent: 'center' } },
            headerPersonaHost: { display: { base: 'inline-flex', lg: 'none' }, flexShrink: '0', alignItems: 'center' },
            navigationLink: { display: 'inline-flex', minWidth: '2.75rem', minHeight: '2.75rem', alignItems: 'center', justifyContent: 'center', borderRadius: 'l2', color: 'fg.muted', padding: '0.5rem', transition: 'colors', _hover: { background: 'bg.subtle', color: 'fg.default' }, _focusVisible: { outline: '2px solid', outlineColor: 'border.focus', outlineOffset: '2px' }, '&[aria-current="page"]': { background: 'bg.subtle', color: 'fg.default', fontWeight: 'semibold' } },
            navigationLinkLabelled: { width: '100%', justifyContent: 'flex-start', gap: '0.75rem', padding: '0.5rem 0.75rem' },
            navigationLinkIcon: { position: 'relative', width: '100%', aspectRatio: '1' },
            navigationIcon: { flexShrink: '0', width: '1.5rem', height: '1.5rem', color: 'currentColor' },
            sidebarDesktop: { flexShrink: '0', height: '100%', minHeight: '0', display: { base: 'none', lg: 'block' } },
            sidebarLabelled: { width: '16rem' },
            sidebarCompact: { width: '4rem' },
            logoLink: { display: 'flex', alignItems: 'center', justifyContent: 'center', width: '2.75rem', height: '2.75rem', marginBottom: '2rem' },
            logo: { width: '2.5rem', height: '2.5rem', objectFit: 'contain' },
            mobileDialog: { '&.dialog__content': { position: 'fixed', insetBlock: '0', insetInlineStart: '0', zIndex: '50', width: '5rem', height: '100dvh', overflowY: 'auto', margin: '0', padding: '0.5rem' } },
            mobileDialogLabelled: { '&.dialog__content': { width: '14rem', maxWidth: '90vw' } },
            mobileDialogCompact: { '&.dialog__content': { width: '5rem' } },
            mobileContent: { height: 'calc(100dvh - 4rem)' },
            mobileClose: { width: '2.5rem', height: '2.5rem', padding: '0.5rem' },
            mobileTrigger: { display: { base: 'inline-flex', lg: 'none' }, padding: '0.5rem' },
            personaTrigger: { position: 'relative', display: 'inline-flex', flexShrink: '0', alignItems: 'center', justifyContent: 'center', minWidth: '2.75rem', minHeight: '2.75rem', padding: '0.125rem', borderRadius: 'full' },
            personaTriggerLabelled: { width: '100%', minWidth: '0', justifyContent: 'flex-start', gap: '0.75rem', padding: '0.25rem 0.5rem' },
            personaAvatar: { width: '2.5rem', height: '2.5rem' },
            personaStatus: { width: '0.75rem', height: '0.75rem', borderWidth: '2px', borderColor: { base: 'bg.surface', lg: 'bg.default' }, background: 'green.9' },
            personaDetails: { display: 'flex', minWidth: '0', flexDirection: 'column', alignItems: 'flex-start', gap: '0.125rem', overflow: 'hidden', textAlign: 'left' },
            personaName: { maxWidth: '100%', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontWeight: 'medium' },
            personaPresence: { color: 'fg.muted', fontSize: '0.75rem', lineHeight: '1rem' },
            accountMenu: { zIndex: '60', boxSizing: 'border-box', minWidth: '15rem', maxWidth: 'min(22rem, calc(100vw - 2rem))', overflow: 'hidden', padding: '0.375rem' },
            accountSummary: { display: 'flex', minWidth: '0', height: 'auto', minHeight: '3.5rem', flexDirection: 'column', alignItems: 'flex-start', justifyContent: 'center', gap: '0.125rem', margin: '0 0 0.25rem', padding: '0.5rem 0.75rem 0.375rem' },
            accountSummaryName: { minWidth: '0', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
            accountSummaryEmail: { minWidth: '0', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', color: 'text.muted', fontSize: '0.875rem' },
            menuItem: { display: 'flex', boxSizing: 'border-box', width: '100%', alignItems: 'center', padding: '0.625rem 0.75rem', '&[data-tone="critical"]': { color: 'critical' } },
            activityTrigger: { position: 'relative', display: 'inline-grid', flexShrink: '0', minWidth: '2.75rem', minHeight: '2.75rem', placeItems: 'center' },
            activityPopover: { width: '24rem', maxWidth: 'calc(100vw - 2rem)', padding: '0.75rem' },
            activityBadge: { position: 'absolute', insetBlockStart: '0', insetInlineEnd: '0', minWidth: '1rem', paddingInline: '0.25rem' },
            activityHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '0.5rem' },
            activityTitle: { margin: '0', fontWeight: '600' },
            activityRefresh: { padding: '0.25rem 0.5rem' },
            activityDismiss: { padding: '0.25rem 0.5rem' },
            activityLoading: { display: 'grid', gap: '0.75rem', padding: '0.75rem' },
            activityEmpty: { paddingBlock: '1rem' },
            activityScroll: { height: 'min(20rem, 45vh)' },
            activityList: { margin: '0', padding: '0', listStyle: 'none' },
            activityRow: { display: 'flex', gap: '0.5rem', paddingBlock: '0.5rem' },
            activityItem: { display: 'grid', minWidth: '0', flex: '1', gap: '0.125rem', padding: '0.5rem', textAlign: 'left', fontSize: '0.875rem' },
            activitySubject: { overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
            activityMoreWrap: { marginTop: '0.5rem' },
            activityMore: { width: '100%', padding: '0.5rem 0.75rem' },
            connectionWrap: { position: 'relative', display: 'flex', alignItems: 'center', gap: '1rem' },
            connectionPopover: { zIndex: '50', width: '16rem', padding: '1rem' },
            connectionButton: { display: 'flex', width: { base: '2.75rem', sm: 'auto' }, minWidth: '2.75rem', minHeight: '2.75rem', alignItems: 'center', justifyContent: 'center', gap: { base: '0', sm: '0.5rem' }, padding: { base: '0', sm: '0.375rem 0.75rem' } },
            connectionLabel: { display: { base: 'none', sm: 'inline' } },
            connectionDot: { width: '0.5rem', height: '0.5rem', borderRadius: 'full', '&[data-state="connected"]': { background: 'accent.primary' }, '&[data-state="disconnected"]': { background: 'critical' } },
            connectionChevron: { display: { base: 'none', sm: 'inline' }, width: '0.875rem', height: '0.875rem' },
            reconnectDivider: { marginTop: '1rem', paddingTop: '1rem' },
            reconnectButton: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', width: '100%', padding: '0.5rem 0.75rem' },
            icon: { width: '1.5rem', height: '1.5rem' },
            menuIcon: { width: '1.5rem', height: '1.5rem' },
            smallIcon: { width: '0.875rem', height: '0.875rem' },
            dismissIcon: { width: '0.875rem', height: '0.875rem' },
            rootInbox: { height: '100dvh', minHeight: '0', overflow: 'hidden' },
            rootStandard: { height: '100dvh', minHeight: '0', overflow: 'hidden' },
            contentInbox: { overflow: 'hidden' },
            contentStandard: { overflow: 'auto' },
            contentPadded: { padding: { base: '1rem', lg: '2rem' } },
          },
        },
        emptyState: {
          className: 'emptyState', slots: ['root', 'title', 'description', 'action'],
          base: { root: { display: 'flex', minHeight: '10rem', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', border: '1px dashed', borderColor: 'border.default', borderRadius: 'l2', background: 'bg.subtle', color: 'fg.default', padding: '1.5rem', textAlign: 'center' }, title: { margin: '0', fontFamily: 'primary', fontWeight: '600' }, description: { margin: '0', color: 'fg.muted', fontFamily: 'primary' }, action: { display: 'flex', marginTop: '0.5rem' } },
        },
        authShell: {
          className: 'authShell', slots: ['root', 'splash', 'image', 'main', 'form', 'logo'],
          base: {
            root: { display: 'flex', minHeight: '100dvh', background: 'bg.canvas', color: 'text.primary', colorPalette: 'gray', fontFamily: 'primary' },
            splash: { position: 'relative', flex: '0 0 45%', maxWidth: '45vw', overflow: 'hidden' },
            image: { position: 'absolute', inset: '0', width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'left top' },
            main: { display: 'flex', flex: '1', minWidth: '0', alignItems: 'center', justifyContent: 'center', padding: { base: '1rem', md: '2rem' } },
            form: { width: '100%', maxWidth: '32rem' },
            logo: { display: 'block', width: '12rem', maxWidth: '100%', height: 'auto', marginBottom: '2rem' },
          },
        },
      },

      recipes: {
        ...parkRegistryRecipes,
      },

      animationStyles: animationStyles,
      keyframes: {
        ...keyframes,
        'overduePulse': {
          '0%': { boxShadow: '0 0 0 0 currentColor' },
          '70%': { boxShadow: '0 0 0 8px transparent' },
          '100%': { boxShadow: '0 0 0 0 transparent' },
        },
      },
      layerStyles: layerStyles
    },
  },

  staticCss: {
    css: [{ properties: { color: ['canvas', 'panel', 'muted', 'text', 'textMuted', 'focus', 'selected', 'divider', 'critical', 'icon.primary', 'icon.muted', 'icon.disabled', 'icon.selected', 'icon.critical', 'icon.inverse'] } }],
    // Installed Park components receive variant props at runtime. Emit their
    // official slot and recipe classes so every public component is styled.
    recipes: '*',
  },
  conditions: conditions
};
