import assert from 'node:assert/strict';
import type { DurableObjectNamespace } from '@cloudflare/workers-types';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { build } from 'esbuild';
import { Miniflare, convertV4MiniflareOptions } from 'miniflare';
import { RESOURCE_DIMENSIONS, STOCK_DIMENSIONS, type CostPolicy } from '@luminatick/shared';
import { createBudgetOwnerAggregateState, refreshBudgetOwnerAggregateAuthority, reserveOwnerAggregate, retireExpiredOwnerGrants, type BudgetOwnerAggregateState, type TrustedBudgetCoordinatorAuthority } from '../src/budgets/owner-aggregate';
import { encodeCoordinatorState, decodeCoordinatorState, encodedGrantBytes } from '../src/budgets/coordinator-storage';
const NOW=Date.UTC(2026,8,13),root=resolve(import.meta.dirname,'..');
const envelope={workerRequests:4,d1RowsRead:7168,d1RowsWritten:16,d1StorageBytes:8192,doRequests:8,doRowsRead:520,doRowsWritten:520,logEvents:136};
const policy:CostPolicy={schemaVersion:1,policyId:'synthetic-policy',revision:1,deploymentId:'synthetic-deployment',mode:'conservative',catalogueVersion:'synthetic',maxGrantLifetimeMs:60000,budgets:RESOURCE_DIMENSIONS.map(dimension=>({dimension,allocationId:'allocation-'+dimension,window:STOCK_DIMENSIONS.includes(dimension)?{kind:'stock' as const,id:'stock-'+dimension}:{kind:'interval' as const,id:'day',startsAt:NOW-1,endsAt:NOW+86400000},limit:1000000000,recoveryPercent:20,provenance:'owner-allocation' as const}))};
const authority=(now:number):TrustedBudgetCoordinatorAuthority=>({aggregateId:'synthetic-aggregate',ownerPolicy:policy,authorityCheckedAt:now,authorityRevision:1,authorityExpiresAt:now+60000,maxReservations:64,tenantAllocations:['a','b'].map(tenantId=>({reservationNamespace:'synthetic-reservations-'+tenantId,effectivePolicy:{...policy,tenantId,restrictionRevision:1,disabledFeatures:[]}}))});
const request=(sequence:number,now:number)=>{const holderId='isolate:a3200000-0000-4000-8000-'+String(sequence).padStart(12,'0');return{tenantId:sequence%2?'a':'b',holderId,idempotencyKey:holderId+':block:1',purpose:'new-work' as const,envelope,expectedPolicyId:policy.policyId,expectedPolicyRevision:1,expectedRestrictionRevision:1,now};};
function baseline(state:BudgetOwnerAggregateState){const wire=JSON.parse(encodeCoordinatorState(state));wire.format=3;for(const t of[wire.state.ownerIngress,...wire.state.tenantStates])for(const row of t.grants)if(Array.isArray(row[2]))row[2]=row[1]+row[2][0];return JSON.stringify(wire);}
function headroom(state:BudgetOwnerAggregateState){let total=8192;const allocations=new Map<string,number>();for(const t of[state.ownerIngress,...state.tenantStates])for(const g of t.grants){if(g.compacted||g.status==='reconciled'||g.purpose!=='new-work')continue;for(const a of t.allocations.filter(a=>g.allocations.some(r=>r.dimension===a.dimension&&r.allocationId===a.allocationId&&r.windowId===a.window.id)))allocations.set(JSON.stringify([t.tenantId,a.dimension,a.allocationId,a.window.id]),2*Buffer.byteLength(JSON.stringify(a)));const paired=t.grants.filter(p=>p.recoversReservationId===g.reservationId).reduce((n,p)=>n+encodedGrantBytes(p),0);total+=Math.max(0,encodedGrantBytes(g)+256-paired);}return total+[...allocations.values()].reduce((a,b)=>a+b,0);}
function fixture(){let state=createBudgetOwnerAggregateState(authority(NOW)),now=NOW;
 for(let i=1;i<=700;i++){now=NOW+i*61000;state=refreshBudgetOwnerAggregateAuthority(state,authority(now));const r=reserveOwnerAggregate(state,request(i,now));assert.equal(r.outcome.status,'granted');state=retireExpiredOwnerGrants(r.state,now+60001);if(Buffer.byteLength(baseline(state))+headroom(state)>=121000){now+=60002;state=refreshBudgetOwnerAggregateAuthority(state,authority(now));assert(Buffer.byteLength(baseline(state))+headroom(state)<=122880);return{state:decodeCoordinatorState(baseline(state)),now};}}
 throw new Error('Synthetic pressure fixture did not reach bound');}
async function bundle(old:boolean){return build({stdin:{contents:`import {BudgetCoordinatorDO as Base} from './src/durable_objects/BudgetCoordinatorDO';export class TestDO extends Base {async seed(value){await this.ctx.storage.put('budget-owner-aggregate-v1',JSON.stringify(value));}async attempt(input){try{return{result:await this.reserveFromTrustedAuthority(input)}}catch(error){return{error:String(error)}}}}export default{fetch(){return new Response(null,{status:404})}}`,resolveDir:root,loader:'ts'},bundle:true,format:'esm',platform:'neutral',external:['cloudflare:workers','node:crypto'],write:false,plugins:old?[{name:'format3-baseline',setup(b){b.onLoad({filter:/coordinator-storage\.ts$/},args=>({loader:'ts',contents:readFileSync(args.path,'utf8').replace('format: 4, state:','format: 3, state:').replace('row[2] = [grant.idempotencyKey.slice(grant.holderId.length)];','row[2] = grant.idempotencyKey;')}));}}]:[]});}
async function plain(value:Promise<any>){const result=await value;try{return JSON.parse(JSON.stringify(result));}finally{result?.[Symbol.dispose]?.();}}
test('native format4 preserves charged metadata and admits a cold burst refused by format3',async()=>{
 const {state,now}=fixture();
 const projected=reserveOwnerAggregate(state,request(1001,now));assert.equal(projected.outcome.status,'granted');
 assert(Buffer.byteLength(baseline(projected.state))+headroom(projected.state)>122880,'baseline rejection is encoded growth, not resource or slot exhaustion');
 const old=await bundle(true),next=await bundle(false);
 const options=convertV4MiniflareOptions({workers:[['old',old],['next',next]].map(([name,b])=>({name:name as string,modules:true,script:(b as typeof old).outputFiles[0].text,compatibilityDate:'2024-04-03',durableObjects:{COORDINATOR:'TestDO'}}))});const mf=new Miniflare(options);
 try{await mf.ready;const get=async(name:string)=>{const ns=await mf.getDurableObjectNamespace('COORDINATOR',name) as unknown as DurableObjectNamespace;return ns.get(ns.idFromName('synthetic')) as any;};const prior=await get('old'),current=await get('next');await prior.seed(state);await current.seed(state);
 const inputs=[1001,1002,1003].map(i=>request(i,now));const oldResults=await Promise.all(inputs.map(input=>plain(prior.attempt(input))));const newResults=await Promise.all(inputs.map(input=>plain(current.attempt(input))));
 assert(oldResults.every(r=>r.result?.status==='rejected'&&r.result.reason==='capacity-exhausted'),'baseline must reject metadata growth');assert(newResults.every(r=>r.result?.status==='granted'),'format4 must admit same burst');
 const after=await plain(current.inspectForTrustedRuntime());for(const before of state.tenantStates){const tenant=after.tenantStates.find((t:any)=>t.tenantId===before.tenantId);assert.deepEqual(tenant.closedCharges,before.closedCharges);for(const g of before.grants)assert.deepEqual(tenant.grants.find((n:any)=>n.reservationId===g.reservationId),g);}
 prior[Symbol.dispose]?.();current[Symbol.dispose]?.();await mf.setOptions(options);const reloaded=await get('next');const loaded=await plain(reloaded.inspectForTrustedRuntime());assert.deepEqual(loaded,after);const replay=await plain(reloaded.attempt(inputs[0]));assert.equal(replay.result?.status,'idempotent');assert.equal((await plain(reloaded.attempt(inputs[0]))).result?.reason,'delivery-exhausted');
 console.log(JSON.stringify({syntheticRecords:state.tenantStates.reduce((n,t)=>n+t.grants.length,0),baselineBytes:Buffer.byteLength(baseline(state)),format4Bytes:Buffer.byteLength(encodeCoordinatorState(state)),baselineRefusals:oldResults.filter(r=>r.result?.status==='rejected').length,format4Grants:newResults.length,reloadAndReplay:true}));
 }finally{await mf.dispose();}
});
