import assert from 'node:assert/strict';
import { SignJWT } from 'jose';
import { readFileSync,readdirSync } from 'node:fs';
import { join,resolve } from 'node:path';
import test from 'node:test';
import { build } from 'esbuild';
import { Miniflare,convertV4MiniflareOptions } from 'miniflare';
import { splitSql } from './split-sql';

const root=resolve(import.meta.dirname,'..'),secret='summary-read-runtime-secret-32',now=Date.now();
const dimensions=['workerRequests','d1RowsRead','d1RowsWritten','doRequests','doRowsRead','doRowsWritten','logEvents'];
async function token(){return new SignJWT({sub:'summary-actor',role:'admin',tenant_id:'summary-a',session_version:1,mfa_verified:true}).setProtectedHeader({alg:'HS256'}).setAudience('app').setIssuedAt().setExpirationTime('1h').sign(new TextEncoder().encode(secret));}
async function fixture(){
 const bundled=await build({entryPoints:[resolve(import.meta.dirname,'dashboard-summary-read-runtime-entry.ts')],bundle:true,format:'esm',platform:'neutral',external:['cloudflare:workers','node:crypto'],write:false});
 const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'summary-proof',modules:true,compatibilityDate:'2024-04-03',compatibilityFlags:['nodejs_compat'],script:bundled.outputFiles[0].text,bindings:{BUDGET_ADMISSION_POLICY:'ticket-mutations-v1',DISABLE_RATE_LIMIT:'true',JWT_SECRET:secret},d1Databases:{DB:'summary-d1'},r2Buckets:{ATTACHMENTS_BUCKET:'summary-r2'},durableObjects:{BUDGET_COORDINATOR_DO:'BudgetCoordinatorDO',BUDGET_GRANT_HOLDER_DO:'BudgetGrantHolderDO',NOTIFICATION_DO:'NotificationDO'},unsafeEphemeralDurableObjects:true}]}));
 try{const db=await mf.getD1Database('DB');for(const file of readdirSync(join(root,'migrations')).filter(file=>file.endsWith('.sql')).sort())await db.batch(splitSql(readFileSync(join(root,'migrations',file),'utf8')).map(sql=>db.prepare(sql)));
 const limits=Object.fromEntries(dimensions.map(dimension=>[dimension,10_000_000]));const owner={schemaVersion:1,policyId:'summary-policy',revision:1,deploymentId:'summary-deployment',mode:'conservative',catalogueVersion:'synthetic',maxGrantLifetimeMs:60_000,budgets:dimensions.map(dimension=>({dimension,limit:10_000_000,allocationId:dimension,recoveryPercent:20,provenance:'owner-allocation',window:{kind:'interval',id:'window',startsAt:now-1_000,endsAt:now+3_600_000}}))};const restriction={schemaVersion:1,tenantId:'summary-a',ownerPolicyId:'summary-policy',ownerPolicyRevision:1,revision:1,mode:'conservative',limits,disabledFeatures:[]};
 await db.batch([db.prepare("INSERT INTO budget_deployment_authority VALUES('summary-deployment',1,'active',?)").bind(now),db.prepare("INSERT INTO budget_owner_policies(deployment_id,policy_id,policy_revision,authority_revision,coordinator_id,max_reservations,authority_max_age_ms,policy_json) VALUES('summary-deployment','summary-policy',1,1,'summary-coordinator',64,30000,?)").bind(JSON.stringify(owner)),db.prepare("INSERT INTO budget_tenant_allocations(deployment_id,tenant_id,policy_id,policy_revision,authority_revision,reservation_namespace,restriction_json,state) VALUES('summary-deployment','summary-a','summary-policy',1,1,'summary-a',?,'active')").bind(JSON.stringify(restriction)),db.prepare("INSERT INTO users(tenant_id,id,email,role,session_version,mfa_enabled) VALUES('summary-a','summary-actor','a@example.test','admin',1,1)"),db.prepare("INSERT INTO users(tenant_id,id,email,role) VALUES('summary-b','summary-actor','b@example.test','admin')"),db.prepare("INSERT INTO tickets(tenant_id,id,subject,customer_email,source) VALUES('summary-a','summary-ticket','Synthetic','customer@example.test','fixture')"),db.prepare("INSERT INTO tickets(tenant_id,id,subject,customer_email,source) VALUES('summary-b','foreign-only','Foreign','customer@example.test','fixture')"),db.prepare("INSERT INTO sla_policies(tenant_id,calendar_json,response_target_ms,resolution_target_ms,response_reopen_policy,resolution_reopen_policy) VALUES('summary-a','{\"timeZone\":\"UTC\",\"weekly\":{},\"exceptions\":[],\"dst\":{\"ambiguousLocalTime\":\"earlier\",\"nonexistentLocalTime\":\"next-valid\"}}',60000,60000,'continue','continue')"),db.prepare("INSERT INTO ticket_sla_clocks(tenant_id,ticket_id,response_started_at,resolution_started_at,policy_revision,policy_calendar_json,policy_response_target_ms,policy_resolution_target_ms,policy_response_reopen_policy,policy_resolution_reopen_policy) VALUES('summary-a','summary-ticket','2026-09-11T00:00:00.000Z','2026-09-11T00:00:00.000Z',0,(SELECT calendar_json FROM sla_policies WHERE tenant_id='summary-a'),60000,60000,'continue','continue')")]);
 await db.prepare("UPDATE ticket_support_state SET snoozed_until='2099-01-01T00:00:00.000Z',resurface_reason='due' WHERE tenant_id='summary-a' AND ticket_id='summary-ticket'").run();
 await db.batch(Array.from({length:600},(_,i)=>db.prepare("INSERT INTO ticket_sla_pause_intervals(tenant_id,ticket_id,started_at,ended_at,reason,support_state_revision) VALUES('summary-a','summary-ticket',?,?,'waiting',1)").bind(`2026-09-10T${String(Math.floor(i/60)).padStart(2,'0')}:${String(i%60).padStart(2,'0')}:00.000Z`,`2026-09-10T${String(Math.floor(i/60)).padStart(2,'0')}:${String(i%60).padStart(2,'0')}:30.000Z`)));
 await db.batch(Array.from({length:24},(_,i)=>[
   db.prepare("INSERT INTO tickets(tenant_id,id,subject,customer_email,source) VALUES('summary-a',?,'Synthetic batch ticket','customer@example.test','fixture')").bind(`summary-batch-${i}`),
   db.prepare("INSERT INTO ticket_sla_clocks(tenant_id,ticket_id,response_started_at,resolution_started_at,policy_revision,policy_calendar_json,policy_response_target_ms,policy_resolution_target_ms,policy_response_reopen_policy,policy_resolution_reopen_policy) VALUES('summary-a',?,'2026-09-11T00:00:00.000Z','2026-09-11T00:00:00.000Z',0,(SELECT calendar_json FROM sla_policies WHERE tenant_id='summary-a'),60000,60000,'continue','continue')").bind(`summary-batch-${i}`),
 ]).flat());
 return {mf,db};}catch(error){await mf.dispose();throw error;}
}
async function request(mf:Miniflare,path:string,init:RequestInit={}){return mf.dispatchFetch(`http://runtime.test${path}`,{...init,headers:{authorization:`Bearer ${await token()}`,...init.headers}});}
test('dashboard summary reads are tenant-scoped, dynamically metered, and fail closed on a current-session or pause-history race',async t=>{const f=await fixture();try{
 const stats=await request(f.mf,'/api/stats');assert.equal(stats.status,200,await stats.clone().text());assert.ok(JSON.stringify(await stats.json()).includes('open'));
 const supportState=await request(f.mf,'/api/tickets/summary-ticket/support-state');assert.equal(supportState.status,200,await supportState.clone().text());assert.deepEqual(await supportState.json(),{
   ticket_id:'summary-ticket',definition_id:'legacy-open',lifecycle:'open',internal_label:'Open',public_label:'Open',waiting_reason:null,next_action:null,
   snoozed_until:'2099-01-01T00:00:00.000Z',resurface_reason:'due',changed_at:(await f.db.prepare("SELECT changed_at FROM ticket_support_state WHERE tenant_id='summary-a' AND ticket_id='summary-ticket'").first<any>()).changed_at,revision:1,
 },'the admitted workspace read retains durable shared-snooze facts');
 const foreignState=await request(f.mf,'/api/tickets/foreign-only/support-state');assert.equal(foreignState.status,404);await foreignState.body?.cancel();
 const ticketIds=['summary-ticket',...Array.from({length:24},(_,i)=>`summary-batch-${i}`)];
 const fullBatch=await request(f.mf,'/api/ticket-sla/projections',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({ticketIds})});
 assert.equal(fullBatch.status,200,await fullBatch.clone().text());assert.deepEqual(Object.keys(await fullBatch.json()).sort(),ticketIds.sort(),'the maximum admitted SLA batch is complete');
 const sla=await request(f.mf,'/api/tickets/summary-ticket/sla');assert.equal(sla.status,200,await sla.clone().text());assert.equal((await f.db.prepare("SELECT pause_rows_upper_bound FROM dashboard_sla_pause_read_counters WHERE tenant_id='summary-a' AND ticket_id='summary-ticket'").first<any>()).pause_rows_upper_bound,600);
 const foreign=await request(f.mf,'/api/tickets/foreign-only/sla');assert.equal(foreign.status,404);await foreign.body?.cancel();
 await f.mf.dispatchFetch('http://runtime.test/__summary-control',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'pause-growth'})});const growth=await request(f.mf,'/api/tickets/summary-ticket/sla');assert.equal(growth.status,503);await growth.body?.cancel();
 const retried=await request(f.mf,'/api/tickets/summary-ticket/sla');assert.equal(retried.status,200);await retried.body?.cancel();
 await f.mf.dispatchFetch('http://runtime.test/__summary-control',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'revoke'})});const revoked=await request(f.mf,'/api/stats');assert.equal(revoked.status,503);await revoked.body?.cancel();
 const operation=await f.db.prepare("SELECT operation_envelope_json FROM budget_grant_operations WHERE tenant_id='summary-a' ORDER BY rowid DESC LIMIT 1").first<any>();assert.ok(JSON.parse(operation.operation_envelope_json).d1RowsRead>=4_096);
 const proof=await (await f.mf.dispatchFetch('http://runtime.test/__summary-control')).json<any>();const measured=proof.measurements.filter((m:any)=>m.path.endsWith('/sla'));assert.ok(measured.some((m:any)=>m.rowsRead>0));t.diagnostic(`native D1 SLA metadata: ${measured.at(-1).rowsRead} reads, ${measured.at(-1).rowsWritten} writes; 601-row history retained`);
 }finally{await f.mf.dispose();}});
